# Bash completion for Postman CLI (postman v1.62.0)
# Auto-generated by scripts/generate.mjs — DO NOT EDIT
# Source: spec/commands.json
# https://github.com/yokawasa/postman-cli-completion
#
# Install:
#   source /path/to/postman.bash
# Or copy into /usr/local/etc/bash_completion.d/ (Homebrew) or
# /etc/bash_completion.d/ (Linux).

# shellcheck shell=bash disable=SC2207

_postman_filematch() {
  local cur="$2"
  COMPREPLY=( $(compgen -f -X "$1" -- "$cur") )
  COMPREPLY+=( $(compgen -d -- "$cur") )
}

_postman() {
  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  local top_commands="login signup logout init whoami feedback update skills collection environment globals api runner spec monitor workspace ws team performance flows fl request sdk mock application app simulate describe context-graph search webhook dataset dependency"
  local global_flags="-v --version --silent --color -h --help -h --help"

  local i cmd="" subcmd=""
  for ((i=1; i<COMP_CWORD; i++)); do
    case "${COMP_WORDS[i]}" in -*) continue ;; esac
    if [[ -z "$cmd" ]]; then
      cmd="${COMP_WORDS[i]}"
    elif [[ -z "$subcmd" ]]; then
      subcmd="${COMP_WORDS[i]}"
      break
    fi
  done

  if [[ -z "$cmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "$top_commands" -- "$cur") )
    fi
    return 0
  fi

  case "$cmd" in
    login) _postman_login ;;
    signup) _postman_signup ;;
    logout) _postman_logout ;;
    init) _postman_init ;;
    whoami) _postman_whoami ;;
    feedback) _postman_feedback ;;
    update) _postman_update ;;
    skills) _postman_skills ;;
    collection) _postman_collection ;;
    environment) _postman_environment ;;
    globals) _postman_globals ;;
    api) _postman_api ;;
    runner) _postman_runner ;;
    spec) _postman_spec ;;
    monitor) _postman_monitor ;;
    workspace|ws) _postman_workspace ;;
    team) _postman_team ;;
    performance) _postman_performance ;;
    flows|fl) _postman_flows ;;
    request) _postman_request ;;
    sdk) _postman_sdk ;;
    mock) _postman_mock ;;
    application|app) _postman_application ;;
    simulate) _postman_simulate ;;
    describe) _postman_describe ;;
    context-graph) _postman_context_graph ;;
    search) _postman_search ;;
    webhook) _postman_webhook ;;
    dataset) _postman_dataset ;;
    dependency) _postman_dependency ;;
  esac
}

_postman_login() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--alias --with-api-key --region --verbose -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --region)
      COMPREPLY=( $(compgen -W "us eu" -- "$cur") )
      return 0 ;;
  esac
}

_postman_signup() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--guest --json -h --help" -- "$cur") )
    return 0
  fi
}

_postman_logout() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--alias -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_init() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json --dry-run --no-fetch --spec --visibility --no-cloud --report-events -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --spec)
      _postman_filematch '!*.@(yaml|yml|json)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_whoami() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json -h --help" -- "$cur") )
    return 0
  fi
}

_postman_feedback() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--type --context --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--check -h --help" -- "$cur") )
    return 0
  fi
}

_postman_skills() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "status update" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    status) _postman_skills_status ;;
    update) _postman_skills_update ;;
  esac
}

_postman_skills_status() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json --strict -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_skills_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json --dry-run --force -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_collection() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "new migrate lint ai-readiness get request list run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    new) _postman_collection_new ;;
    migrate) _postman_collection_migrate ;;
    lint) _postman_collection_lint ;;
    ai-readiness) _postman_collection_ai_readiness ;;
    get) _postman_collection_get ;;
    request) _postman_collection_request ;;
    list) _postman_collection_list ;;
    run) _postman_collection_run ;;
  esac
}

_postman_collection_new() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --force --verbose --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_collection_migrate() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_collection_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-f --fail-severity -r --reporter -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_collection_ai_readiness() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output --min-score -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_collection_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_collection_request() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "add update rm remove" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    add) _postman_collection_request_add ;;
    update) _postman_collection_request_update ;;
    rm|remove) _postman_collection_request_rm ;;
  esac
}

_postman_collection_request_add() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--collection --folder --type -w --workspace --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_collection_request_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--collection --folder --rename --url --method --param -d --body --variables --description --headers --auth --scripts -w --workspace --type --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --param)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --headers)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_collection_request_rm() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--collection --folder -w --workspace --type --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_collection_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace -f --filter --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_collection_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment -g --globals -r --reporters --output --reporter-json-structure -n --iteration-count -d --iteration-data --iteration-data-dataset --iteration-data-view --dataset -i --global-var --env-var --integration-id --postman-api-key --alias --bail --ignore-redirects -x --suppress-exit-code --silent --disable-unicode --delay-request --timeout --timeout-request --timeout-script --working-dir --no-insecure-file-read -k --insecure --ssl-client-cert-list --ssl-client-cert --ssl-client-key --ssl-client-passphrase --ssl-extra-ca-certs --cookie-jar --export-cookie-jar --verbose --mock --port --use-mock --simulate --report-events --no-report-events -h --help --reporter-json-export --reporter-junit-export --reporter-html-export --reporter-json-omitRequestBodies --reporter-html-omitRequestBodies --reporter-json-omitResponseBodies --reporter-html-omitResponseBodies --reporter-json-omitHeaders --reporter-html-omitHeaders --reporter-json-omitAllHeadersAndBody --reporter-html-omitAllHeadersAndBody" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -g|--globals)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -r|--reporters)
      COMPREPLY=( $(compgen -W "cli json junit html" -- "$cur") )
      return 0 ;;
    -d|--iteration-data)
      _postman_filematch '!*.@(json|csv)' "$cur"
      return 0 ;;
    --iteration-data-dataset)
      _postman_filematch '!*.@(json|csv)' "$cur"
      return 0 ;;
    --dataset)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --bail)
      COMPREPLY=( $(compgen -W "folder failure" -- "$cur") )
      return 0 ;;
    --working-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
    --ssl-client-cert-list)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --ssl-client-cert)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --ssl-client-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --ssl-extra-ca-certs)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --cookie-jar)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --export-cookie-jar)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --mock)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --simulate)
      _postman_filematch '!*.@(sim.yaml|yaml|yml)' "$cur"
      return 0 ;;
    --reporter-json-export)
      _postman_filematch '!*.@(json|xml|html)' "$cur"
      return 0 ;;
    --reporter-junit-export)
      _postman_filematch '!*.@(json|xml|html)' "$cur"
      return 0 ;;
    --reporter-html-export)
      _postman_filematch '!*.@(json|xml|html)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_environment() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "new list get var lint" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    new) _postman_environment_new ;;
    list) _postman_environment_list ;;
    get) _postman_environment_get ;;
    var) _postman_environment_var ;;
    lint) _postman_environment_lint ;;
  esac
}

_postman_environment_new() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --force --verbose --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_environment_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace -f --filter --verbose --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_environment_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--verbose --json --show-secrets -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_environment_var() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "set get unset" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    set) _postman_environment_var_set ;;
    get) _postman_environment_var_get ;;
    unset) _postman_environment_var_unset ;;
  esac
}

_postman_environment_var_set() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment --verbose --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_environment_var_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment --verbose --json --show-secrets -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_environment_var_unset() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment --verbose --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_environment_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-f --fail-severity -o --output -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_globals() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "lint" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    lint) _postman_globals_lint ;;
  esac
}

_postman_globals_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-f --fail-severity -o --output -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_api() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "lint publish" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    lint) _postman_api_lint ;;
    publish) _postman_api_publish ;;
  esac
}

_postman_api_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--integration-id -f --fail-severity -x --suppress-exit-code -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_api_publish() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--name --release-notes --collections --api-definition --do-not-poll -x --suppress-exit-code -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --collections)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_runner() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "start list regions" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    start) _postman_runner_start ;;
    list) _postman_runner_list ;;
    regions) _postman_runner_regions ;;
  esac
}

_postman_runner_start() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--id --key --region --proxy --egress-proxy --egress-proxy-authz-url --ssl-extra-ca-certs --dataset-jdbc-driver-dir --metrics --metrics-port --report-events --no-report-events -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --ssl-extra-ca-certs)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --dataset-jdbc-driver-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
}

_postman_runner_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key -w --workspace --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_runner_regions() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_spec() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "lint ai-readiness list get file create generate" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    lint) _postman_spec_lint ;;
    ai-readiness) _postman_spec_ai_readiness ;;
    list) _postman_spec_list ;;
    get) _postman_spec_get ;;
    file) _postman_spec_file ;;
    create) _postman_spec_create ;;
    generate) _postman_spec_generate ;;
  esac
}

_postman_spec_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-f --fail-severity -o --output --workspace-id --report-events --no-report-events -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_spec_ai_readiness() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output --min-score -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_spec_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_spec_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_spec_file() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "add update rm" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    add) _postman_spec_file_add ;;
    update) _postman_spec_file_update ;;
    rm) _postman_spec_file_rm ;;
  esac
}

_postman_spec_file_add() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-c --content --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_spec_file_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-c --content --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_spec_file_rm() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_spec_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-n --name -t --type --spec-version -f --format -w --workspace --force --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_spec_generate() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "collection" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    collection) _postman_spec_generate_collection ;;
  esac
}

_postman_spec_generate_collection() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-n --name --folder-strategy -w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "run create update delete jobs runs list get metrics pause resume" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    run) _postman_monitor_run ;;
    create) _postman_monitor_create ;;
    update) _postman_monitor_update ;;
    delete) _postman_monitor_delete ;;
    jobs) _postman_monitor_jobs ;;
    runs) _postman_monitor_runs ;;
    list) _postman_monitor_list ;;
    get) _postman_monitor_get ;;
    metrics) _postman_monitor_metrics ;;
    pause) _postman_monitor_pause ;;
    resume) _postman_monitor_resume ;;
  esac
}

_postman_monitor_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key -x --suppress-exit-code -t --timeout --async --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-c --collection --name -e --environment -w --workspace --schedule --timezone --runner --notify-email --notification-limit --retry --timeout --delay --strict-ssl --insecure --follow-redirects --block-redirects --dataset-id --dataset-view-id --iteration-count --iteration-strategy --no-run-now --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--name --schedule --timezone --runner --notify-email --clear-notifications -e --environment --clear-environment --notification-limit --retry --timeout --delay --strict-ssl --insecure --follow-redirects --block-redirects --dataset-id --dataset-view-id --iteration-count --iteration-strategy --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_jobs() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_monitor_jobs_list ;;
    get) _postman_monitor_jobs_get ;;
  esac
}

_postman_monitor_jobs_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --result --trigger --since --limit --cursor --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_jobs_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_runs() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_monitor_runs_get ;;
  esac
}

_postman_monitor_runs_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --attempt --failed-only --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key -w --workspace -c --collection -e --environment --runner --owner --team --active --limit --cursor --columns --no-headers -f --filter --sort --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_metrics() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --since --until -f --filter --limit --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_pause() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_monitor_resume() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_workspace() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list prepare push lint get create pull connect-git diff" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_workspace_list ;;
    prepare) _postman_workspace_prepare ;;
    push) _postman_workspace_push ;;
    lint) _postman_workspace_lint ;;
    get) _postman_workspace_get ;;
    create) _postman_workspace_create ;;
    pull) _postman_workspace_pull ;;
    connect-git) _postman_workspace_connect_git ;;
    diff) _postman_workspace_diff ;;
  esac
}

_postman_workspace_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-f --filter -t --type --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_workspace_prepare() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--verbose -h --help" -- "$cur") )
    return 0
  fi
}

_postman_workspace_push() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--no-prepare -y --yes --push-strategy --verbose --report-events --no-report-events -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_workspace_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-f --fail-severity -o --output --meta --workspace-id --fix -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_workspace_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--elements --json --timeout -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_workspace_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--visibility --name --summary --team-id --team-role --path --no-connect --force -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --path)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_workspace_pull() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes --source-workspace --verbose -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_workspace_connect_git() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--verbose -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_workspace_diff() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--push-strategy --summary --json --exit-code --verbose --timeout -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_team() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_team_list ;;
  esac
}

_postman_team_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--can-create-workspace --json --timeout -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_performance() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "run list" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    run) _postman_performance_run ;;
    list) _postman_performance_list ;;
  esac
}

_postman_performance_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment -g --globals --setup-collection --teardown-collection --vu-count -d --duration -p --load-profile --data-file --dataset-id --dataset-view-id --dataset-distribution --postman-api-key --output --runner --pass-if --use-mock -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --data-file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_performance_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-c --collection-id --cursor --json --timeout -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_flows() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list trigger deploy run update list-runs get-run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_flows_list ;;
    trigger) _postman_flows_trigger ;;
    deploy) _postman_flows_deploy ;;
    run) _postman_flows_run ;;
    update) _postman_flows_update ;;
    list-runs) _postman_flows_list_runs ;;
    get-run) _postman_flows_get_run ;;
  esac
}

_postman_flows_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace -p --paginate -f --filter -s --sort --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_flows_trigger() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-i --input -f --input-file -q --query --headers -n --dry-run --show-secrets -r --result -s --scenario --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -i|--input)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    -f|--input-file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -q|--query)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --headers)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_flows_deploy() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-p --path -t --timeout -a --auth --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -p|--path)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_flows_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-i --input -f --input-file -s --scenario --iteration-data-dataset --iteration-data-view -m --map-column -e --environment --working-dir --no-insecure-file-read --verbose --no-truncate --output --reporters -x --suppress-exit-code --workspace --report-events --no-report-events --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -i|--input)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    -f|--input-file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --iteration-data-dataset)
      _postman_filematch '!*.@(json|csv)' "$cur"
      return 0 ;;
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --working-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_flows_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-t --trigger -a --auth --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_flows_list_runs() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace -f --flow -r --range --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_flows_get_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-r --run-id -l --logs --filter --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_request() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-H --header -d --body -f --form -e --environment --timeout --redirects-ignore --redirects-max --redirects-follow-method --redirects-remove-referrer --retry --retry-delay --script-pre-request --script-post-request --dataset -o --output --verbose --response-only --debug --report-events --no-report-events -h --help --auth-basic-username --auth-basic-password --auth-bearer-token --auth-digest-username --auth-digest-password --auth-oauth1-consumerKey --auth-oauth1-consumerSecret --auth-oauth1-token --auth-oauth1-tokenSecret --auth-oauth2-accessToken --auth-oauth2-tokenType --auth-hawk-authId --auth-hawk-authKey --auth-hawk-algorithm --auth-aws-accessKey --auth-aws-secretKey --auth-aws-region --auth-aws-service --auth-aws-sessionToken --auth-ntlm-username --auth-ntlm-password --auth-ntlm-domain --auth-ntlm-workstation --auth-apikey-key --auth-apikey-value --auth-apikey-in" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --dataset)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -o|--output)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_sdk() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "init generate build track list ls fetch get connect connections" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    init) _postman_sdk_init ;;
    generate|build) _postman_sdk_generate ;;
    track) _postman_sdk_track ;;
    list|ls) _postman_sdk_list ;;
    fetch|get) _postman_sdk_fetch ;;
    connect) _postman_sdk_connect ;;
    connections) _postman_sdk_connections ;;
  esac
}

_postman_sdk_init() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes -h --help" -- "$cur") )
    return 0
  fi
}

_postman_sdk_generate() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-l --language --all -o --output-dir --name --sdk-version --config -y --yes --overwrite --verbose --log-level --no-track-changes --no-merge --conflict-strategy --no-emit -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
    --config)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_sdk_track() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-l --language -o --output-dir -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
}

_postman_sdk_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-s --status -o --output --log-level -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_sdk_fetch() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output-dir -l --language --overwrite --verbose --log-level -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
}

_postman_sdk_connect() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-l --language -r --repo --repo-owner --repo-name -b --branch --push-to-base --auto-update-pull-requests --auth-provider --verbose -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_sdk_connections() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list ls delete rm" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list|ls) _postman_sdk_connections_list ;;
    delete|rm) _postman_sdk_connections_delete ;;
  esac
}

_postman_sdk_connections_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--refresh --json --verbose -h --help" -- "$cur") )
    return 0
  fi
}

_postman_sdk_connections_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes --verbose -h --help" -- "$cur") )
    return 0
  fi
}

_postman_mock() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "generate run push deploy get list log delete" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    generate) _postman_mock_generate ;;
    run) _postman_mock_run ;;
    push) _postman_mock_push ;;
    deploy) _postman_mock_deploy ;;
    get) _postman_mock_get ;;
    list) _postman_mock_list ;;
    log) _postman_mock_log ;;
    delete) _postman_mock_delete ;;
  esac
}

_postman_mock_generate() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output -n --name --port --force -u --update -w --workspace --api-key -x --suppress-exit-code -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -u|--update)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_mock_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment -g --globals -p --port --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -g|--globals)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_mock_push() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_mock_deploy() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace -n --name -s --slug --public --auto-deploy -y --yes --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_mock_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_mock_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_mock_log() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--limit --method --status --path --since --until --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_mock_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_application() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "init test setup-capture" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    init) _postman_application_init ;;
    test) _postman_application_test ;;
    setup-capture) _postman_application_setup_capture ;;
  esac
}

_postman_application_init() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--target-collection --target-environment --filter-urlpatterns --filter-methods --filter-headers --command -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_application_test() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--target --target-collection --target-environment --command --deployed-version --network-log --capture-only --output --force --report-events --no-report-events --verbose -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --target-collection)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --target-environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --network-log)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --output)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_application_setup_capture() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--config -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --config)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_simulate() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    run) _postman_simulate_run ;;
  esac
}

_postman_simulate_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_describe() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "instructions collection request folder response workspace environment" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    instructions) _postman_describe_instructions ;;
    collection) _postman_describe_collection ;;
    request) _postman_describe_request ;;
    folder) _postman_describe_folder ;;
    response) _postman_describe_response ;;
    workspace) _postman_describe_workspace ;;
    environment) _postman_describe_environment ;;
  esac
}

_postman_describe_instructions() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_describe_collection() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_describe_collection_get ;;
  esac
}

_postman_describe_collection_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-c --collection-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_describe_request() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get context" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_describe_request_get ;;
    context) _postman_describe_request_context ;;
  esac
}

_postman_describe_request_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-r --request-id -c --collection-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_describe_request_context() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-c --collection-id -r --request-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_describe_folder() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_describe_folder_get ;;
  esac
}

_postman_describe_folder_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--folder-id -c --collection-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_describe_response() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_describe_response_get ;;
  esac
}

_postman_describe_response_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--id -c --collection-id -r --request-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_describe_workspace() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_describe_workspace_get ;;
  esac
}

_postman_describe_workspace_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_describe_environment() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_describe_environment_get ;;
  esac
}

_postman_describe_environment_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_context_graph() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "ask status" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    ask) _postman_context_graph_ask ;;
    status) _postman_context_graph_status ;;
  esac
}

_postman_context_graph_ask() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--wait --api-key --json --no-include-answer --max-steps --interval --timeout -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_context_graph_status() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_search() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "--ownership -n --limit --cursor -o --output --filter --filter-json -h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "requests collections workspaces flows specs mocks environments documents" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    requests) _postman_search_requests ;;
    collections) _postman_search_collections ;;
    workspaces) _postman_search_workspaces ;;
    flows) _postman_search_flows ;;
    specs) _postman_search_specs ;;
    mocks) _postman_search_mocks ;;
    environments) _postman_search_environments ;;
    documents) _postman_search_documents ;;
  esac
}

_postman_search_requests() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_collections() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_workspaces() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_flows() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_specs() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_mocks() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_environments() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_documents() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_webhook() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "create start pause list delete status requests scripts forward" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    create) _postman_webhook_create ;;
    start) _postman_webhook_start ;;
    pause) _postman_webhook_pause ;;
    list) _postman_webhook_list ;;
    delete) _postman_webhook_delete ;;
    status) _postman_webhook_status ;;
    requests) _postman_webhook_requests ;;
    scripts) _postman_webhook_scripts ;;
    forward) _postman_webhook_forward ;;
  esac
}

_postman_webhook_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-t --title -w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_start() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_pause() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_status() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_requests() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list describe replay" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_webhook_requests_list ;;
    describe) _postman_webhook_requests_describe ;;
    replay) _postman_webhook_requests_replay ;;
  esac
}

_postman_webhook_requests_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --cursor --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_requests_describe() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key --verbose -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_requests_replay() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_scripts() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "set" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    set) _postman_webhook_scripts_set ;;
  esac
}

_postman_webhook_scripts_set() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--event -w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_forward() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list get query create delete source view jdbc" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_dataset_list ;;
    get) _postman_dataset_get ;;
    query) _postman_dataset_query ;;
    create) _postman_dataset_create ;;
    delete) _postman_dataset_delete ;;
    source) _postman_dataset_source ;;
    view) _postman_dataset_view ;;
    jdbc) _postman_dataset_jdbc ;;
  esac
}

_postman_dataset_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--api-key --no-populate --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_query() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-q --query -s --source -p --param --api-key --json --debug -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-n --name -d --description --dataset-id --force -w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes --keep-resources --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_source() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list add remove update test" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_dataset_source_list ;;
    add) _postman_dataset_source_add ;;
    remove) _postman_dataset_source_remove ;;
    update) _postman_dataset_source_update ;;
    test) _postman_dataset_source_test ;;
  esac
}

_postman_dataset_source_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_source_add() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset -n --name --source-id --format --type --file --ref-only --force --upload --driver-jar --driver-class --driver-name --url-template --var --prop --vars-file --from-source --java-path --no-test --ssh-target-host-variable --ssh-target-port-variable --json --host --port --user --password --database --table --ssh-host --ssh-port --ssh-user --ssh-private-key --ssh-host-key --ssh-host-key-vault-id --ssh-host-key-secret-id --ssh-insecure-skip-host-key-verification --schema --encrypt --trust-server-certificate --tls-certificate --host-name-in-certificate --tls-min-version --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --driver-jar)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --vars-file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --java-path)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --ssh-private-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --tls-certificate)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_source_remove() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_source_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset -n --name --format --file --ref-only --force --driver-jar --driver-class --driver-name --url-template --var --prop --unset-var --unset-prop --vars-file --ssh-target-host-variable --ssh-target-port-variable --java-path --host --port --user --password --database --table --ssh-host --ssh-port --ssh-user --ssh-private-key --ssh-host-key --ssh-host-key-vault-id --ssh-host-key-secret-id --ssh-insecure-skip-host-key-verification --schema --encrypt --trust-server-certificate --tls-certificate --host-name-in-certificate --tls-min-version --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --driver-jar)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --vars-file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --java-path)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --ssh-private-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --tls-certificate)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_source_test() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset -n --name --java-path --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --java-path)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_view() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list run create delete update" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_dataset_view_list ;;
    run) _postman_dataset_view_run ;;
    create) _postman_dataset_view_create ;;
    delete) _postman_dataset_view_delete ;;
    update) _postman_dataset_view_update ;;
  esac
}

_postman_dataset_view_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset --api-key --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_view_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset -p --param --api-key --json --debug -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_view_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset -n --name -q --query -s --source --view-id --json --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_view_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_view_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-d --dataset -n --name -q --query --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_jdbc() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "inspect" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    inspect) _postman_dataset_jdbc_inspect ;;
  esac
}

_postman_dataset_jdbc_inspect() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--driver-class --url-template --java-path --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --java-path)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_dependency() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "add list install update" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    add) _postman_dependency_add ;;
    list) _postman_dependency_list ;;
    install) _postman_dependency_install ;;
    update) _postman_dependency_update ;;
  esac
}

_postman_dependency_add() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace -y --yes --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_dependency_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--type --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_dependency_install() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--type --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_dependency_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--type --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

complete -F _postman postman
