# Bash completion for Postman CLI (postman v1.40.0)
# Auto-generated by scripts/generate.mjs — DO NOT EDIT
# Source: spec/commands.json
# https://github.com/yokawasa/postman-cli-completion
#
# Install:
#   source /path/to/postman.bash
# Or copy into /usr/local/etc/bash_completion.d/ (Homebrew) or
# /etc/bash_completion.d/ (Linux).

# shellcheck shell=bash disable=SC2207

_postman_filematch() {
  local cur="$2"
  COMPREPLY=( $(compgen -f -X "$1" -- "$cur") )
  COMPREPLY+=( $(compgen -d -- "$cur") )
}

_postman() {
  local cur prev
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"

  local top_commands="login logout collection api runner spec monitor workspace performance flows fl request sdk mock application app simulate context search webhook dataset"
  local global_flags="-v --version --silent --color -h --help -h --help"

  local i cmd="" subcmd=""
  for ((i=1; i<COMP_CWORD; i++)); do
    case "${COMP_WORDS[i]}" in -*) continue ;; esac
    if [[ -z "$cmd" ]]; then
      cmd="${COMP_WORDS[i]}"
    elif [[ -z "$subcmd" ]]; then
      subcmd="${COMP_WORDS[i]}"
      break
    fi
  done

  if [[ -z "$cmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "$top_commands" -- "$cur") )
    fi
    return 0
  fi

  case "$cmd" in
    login) _postman_login ;;
    logout) _postman_logout ;;
    collection) _postman_collection ;;
    api) _postman_api ;;
    runner) _postman_runner ;;
    spec) _postman_spec ;;
    monitor) _postman_monitor ;;
    workspace) _postman_workspace ;;
    performance) _postman_performance ;;
    flows|fl) _postman_flows ;;
    request) _postman_request ;;
    sdk) _postman_sdk ;;
    mock) _postman_mock ;;
    application|app) _postman_application ;;
    simulate) _postman_simulate ;;
    context) _postman_context ;;
    search) _postman_search ;;
    webhook) _postman_webhook ;;
    dataset) _postman_dataset ;;
  esac
}

_postman_login() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--alias --with-api-key --region --verbose -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --region)
      COMPREPLY=( $(compgen -W "us eu" -- "$cur") )
      return 0 ;;
  esac
}

_postman_logout() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--alias -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_collection() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "migrate lint ai-readiness run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    migrate) _postman_collection_migrate ;;
    lint) _postman_collection_lint ;;
    ai-readiness) _postman_collection_ai_readiness ;;
    run) _postman_collection_run ;;
  esac
}

_postman_collection_migrate() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_collection_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-f --fail-severity -r --reporter -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_collection_ai_readiness() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output --min-score -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_collection_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment -g --globals -r --reporters --reporter-json-structure -n --iteration-count -d --iteration-data --iteration-data-dataset --iteration-data-view --dataset -i --global-var --env-var --integration-id --postman-api-key --alias --bail --ignore-redirects -x --suppress-exit-code --silent --disable-unicode --delay-request --timeout --timeout-request --timeout-script --working-dir --no-insecure-file-read -k --insecure --ssl-client-cert-list --ssl-client-cert --ssl-client-key --ssl-client-passphrase --ssl-extra-ca-certs --cookie-jar --export-cookie-jar --verbose --mock --simulate -h --help --reporter-json-export --reporter-junit-export --reporter-html-export --reporter-json-omitRequestBodies --reporter-html-omitRequestBodies --reporter-json-omitResponseBodies --reporter-html-omitResponseBodies --reporter-json-omitHeaders --reporter-html-omitHeaders --reporter-json-omitAllHeadersAndBody --reporter-html-omitAllHeadersAndBody" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -g|--globals)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -r|--reporters)
      COMPREPLY=( $(compgen -W "cli json junit html" -- "$cur") )
      return 0 ;;
    -d|--iteration-data)
      _postman_filematch '!*.@(json|csv)' "$cur"
      return 0 ;;
    --iteration-data-dataset)
      _postman_filematch '!*.@(json|csv)' "$cur"
      return 0 ;;
    --dataset)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --bail)
      COMPREPLY=( $(compgen -W "folder failure" -- "$cur") )
      return 0 ;;
    --working-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
    --ssl-client-cert-list)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --ssl-client-cert)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --ssl-client-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --ssl-extra-ca-certs)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --cookie-jar)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --export-cookie-jar)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --mock)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --simulate)
      _postman_filematch '!*.@(sim.yaml|yaml|yml)' "$cur"
      return 0 ;;
    --reporter-json-export)
      _postman_filematch '!*.@(json|xml|html)' "$cur"
      return 0 ;;
    --reporter-junit-export)
      _postman_filematch '!*.@(json|xml|html)' "$cur"
      return 0 ;;
    --reporter-html-export)
      _postman_filematch '!*.@(json|xml|html)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_api() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "lint publish" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    lint) _postman_api_lint ;;
    publish) _postman_api_publish ;;
  esac
}

_postman_api_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--integration-id -f --fail-severity -x --suppress-exit-code -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_api_publish() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--name --release-notes --collections --api-definition --do-not-poll -x --suppress-exit-code -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --collections)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_runner() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "start" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    start) _postman_runner_start ;;
  esac
}

_postman_runner_start() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--id --key --region --proxy --egress-proxy --egress-proxy-authz-url --ssl-extra-ca-certs --metrics --metrics-port -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --ssl-extra-ca-certs)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_spec() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "lint ai-readiness" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    lint) _postman_spec_lint ;;
    ai-readiness) _postman_spec_ai_readiness ;;
  esac
}

_postman_spec_lint() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-f --fail-severity -o --output --workspace-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_spec_ai_readiness() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output --min-score -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_monitor() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    run) _postman_monitor_run ;;
  esac
}

_postman_monitor_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-x --suppress-exit-code -t --timeout -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_workspace() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "prepare push" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    prepare) _postman_workspace_prepare ;;
    push) _postman_workspace_push ;;
  esac
}

_postman_workspace_prepare() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--collections-dir --environments-dir -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --collections-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
    --environments-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
}

_postman_workspace_push() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--collections-dir --environments-dir --no-prepare -y --yes -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --collections-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
    --environments-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
}

_postman_performance() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    run) _postman_performance_run ;;
  esac
}

_postman_performance_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment -g --globals --vu-count -d --duration -p --load-profile --data-file --postman-api-key --pass-if -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --data-file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_flows() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list trigger deploy run update list-runs get-run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_flows_list ;;
    trigger) _postman_flows_trigger ;;
    deploy) _postman_flows_deploy ;;
    run) _postman_flows_run ;;
    update) _postman_flows_update ;;
    list-runs) _postman_flows_list_runs ;;
    get-run) _postman_flows_get_run ;;
  esac
}

_postman_flows_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace -p --paginate -f --filter -s --sort --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_flows_trigger() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-i --input -f --input-file -q --query --headers -n --dry-run --show-secrets -r --result -s --scenario --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -i|--input)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    -f|--input-file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -q|--query)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    --headers)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_flows_deploy() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-p --path -t --timeout -a --auth --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -p|--path)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_flows_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-i --input -f --input-file -s --scenario -e --environment --working-dir --verbose --no-truncate --output --reporters -x --suppress-exit-code --workspace --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -i|--input)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
    -f|--input-file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --working-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_flows_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-t --trigger -a --auth --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_flows_list_runs() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace -f --flow -r --range --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_flows_get_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-r --run-id -l --logs --filter --verbose --debug --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_request() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-H --header -d --body -f --form -e --environment --timeout --redirects-ignore --redirects-max --redirects-follow-method --redirects-remove-referrer --retry --retry-delay --script-pre-request --script-post-request --dataset -o --output --verbose --response-only --debug -h --help --auth-basic-username --auth-basic-password --auth-bearer-token --auth-digest-username --auth-digest-password --auth-oauth1-consumerKey --auth-oauth1-consumerSecret --auth-oauth1-token --auth-oauth1-tokenSecret --auth-oauth2-accessToken --auth-oauth2-tokenType --auth-hawk-authId --auth-hawk-authKey --auth-hawk-algorithm --auth-aws-accessKey --auth-aws-secretKey --auth-aws-region --auth-aws-service --auth-aws-sessionToken --auth-ntlm-username --auth-ntlm-password --auth-ntlm-domain --auth-ntlm-workstation --auth-apikey-key --auth-apikey-value --auth-apikey-in" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --dataset)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -o|--output)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_sdk() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "init generate build track list ls fetch get connect connections" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    init) _postman_sdk_init ;;
    generate|build) _postman_sdk_generate ;;
    track) _postman_sdk_track ;;
    list|ls) _postman_sdk_list ;;
    fetch|get) _postman_sdk_fetch ;;
    connect) _postman_sdk_connect ;;
    connections) _postman_sdk_connections ;;
  esac
}

_postman_sdk_init() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes -h --help" -- "$cur") )
    return 0
  fi
}

_postman_sdk_generate() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-l --language --all -o --output-dir --name --sdk-version --config -y --yes --overwrite --verbose --log-level --no-track-changes --no-merge --conflict-strategy --no-emit -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
    --config)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_sdk_track() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-l --language -o --output-dir -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
}

_postman_sdk_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-s --status -o --output --log-level -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_sdk_fetch() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-o --output-dir -l --language --overwrite --verbose --log-level -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -o|--output-dir)
      COMPREPLY=( $(compgen -d -- "$cur") )
      return 0 ;;
  esac
}

_postman_sdk_connect() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-l --language -r --repo --repo-owner --repo-name -b --branch --push-to-base --enable-npm-publishing --auth-provider --verbose -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_sdk_connections() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list ls delete rm" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list|ls) _postman_sdk_connections_list ;;
    delete|rm) _postman_sdk_connections_delete ;;
  esac
}

_postman_sdk_connections_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--refresh --json --verbose -h --help" -- "$cur") )
    return 0
  fi
}

_postman_sdk_connections_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes --verbose -h --help" -- "$cur") )
    return 0
  fi
}

_postman_mock() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    run) _postman_mock_run ;;
  esac
}

_postman_mock_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment -g --globals -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    -e|--environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    -g|--globals)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_application() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "init test" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    init) _postman_application_init ;;
    test) _postman_application_test ;;
  esac
}

_postman_application_init() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--target-collection --target-environment --filter-urlpatterns --filter-methods --filter-headers --command -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_application_test() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--target --target-collection --target-environment --command --network-log --capture-only --output --force --report-events --verbose -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --target-collection)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --target-environment)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --network-log)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
    --output)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_simulate() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "run" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    run) _postman_simulate_run ;;
  esac
}

_postman_simulate_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_context() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "instructions collection request folder response workspace environment" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    instructions) _postman_context_instructions ;;
    collection) _postman_context_collection ;;
    request) _postman_context_request ;;
    folder) _postman_context_folder ;;
    response) _postman_context_response ;;
    workspace) _postman_context_workspace ;;
    environment) _postman_context_environment ;;
  esac
}

_postman_context_instructions() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_context_collection() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_context_collection_get ;;
  esac
}

_postman_context_collection_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-c --collection-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_context_request() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get context" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_context_request_get ;;
    context) _postman_context_request_context ;;
  esac
}

_postman_context_request_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-r --request-id -c --collection-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_context_request_context() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-c --collection-id -r --request-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_context_folder() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_context_folder_get ;;
  esac
}

_postman_context_folder_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--folder-id -c --collection-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_context_response() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_context_response_get ;;
  esac
}

_postman_context_response_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--id -c --collection-id -r --request-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_context_workspace() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_context_workspace_get ;;
  esac
}

_postman_context_workspace_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_context_environment() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "get" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    get) _postman_context_environment_get ;;
  esac
}

_postman_context_environment_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-e --environment-id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_search() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "--ownership -n --limit --cursor -o --output --filter --filter-json -h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "requests collections workspaces flows specs mocks environments" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    requests) _postman_search_requests ;;
    collections) _postman_search_collections ;;
    workspaces) _postman_search_workspaces ;;
    flows) _postman_search_flows ;;
    specs) _postman_search_specs ;;
    mocks) _postman_search_mocks ;;
    environments) _postman_search_environments ;;
  esac
}

_postman_search_requests() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_collections() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_workspaces() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_flows() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_specs() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_mocks() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_search_environments() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_webhook() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "create start pause list delete status forward" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    create) _postman_webhook_create ;;
    start) _postman_webhook_start ;;
    pause) _postman_webhook_pause ;;
    list) _postman_webhook_list ;;
    delete) _postman_webhook_delete ;;
    status) _postman_webhook_status ;;
    forward) _postman_webhook_forward ;;
  esac
}

_postman_webhook_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-t --title -w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_start() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_pause() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_status() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_webhook_forward() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-w --workspace --api-key -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --api-key)
      _postman_filematch '!*.@(pem|crt|key)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list get query create delete source view" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_dataset_list ;;
    get) _postman_dataset_get ;;
    query) _postman_dataset_query ;;
    create) _postman_dataset_create ;;
    delete) _postman_dataset_delete ;;
    source) _postman_dataset_source ;;
    view) _postman_dataset_view ;;
  esac
}

_postman_dataset_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_get() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_query() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-q --query -p --param --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-n --name -d --description --id --force -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-y --yes --keep-resources -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_source() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list add remove update" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_dataset_source_list ;;
    add) _postman_dataset_source_add ;;
    remove) _postman_dataset_source_remove ;;
    update) _postman_dataset_source_update ;;
  esac
}

_postman_dataset_source_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_source_add() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-n --name --id --format --type --file --ref-only --force --url --host --port --user --password --database --table --slug -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_source_remove() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_dataset_source_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-n --name --format --file --ref-only --force --url --host --port --user --password --database --table --slug -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
    --file)
      _postman_filematch '!*.@(json)' "$cur"
      return 0 ;;
  esac
}

_postman_dataset_view() {
  if [[ -z "$subcmd" ]]; then
    if [[ "$cur" == -* ]]; then
      COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    else
      COMPREPLY=( $(compgen -W "list run create delete update" -- "$cur") )
    fi
    return 0
  fi
  case "$subcmd" in
    list) _postman_dataset_view_list ;;
    run) _postman_dataset_view_run ;;
    create) _postman_dataset_view_create ;;
    delete) _postman_dataset_view_delete ;;
    update) _postman_dataset_view_update ;;
  esac
}

_postman_dataset_view_list() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--json -h --help" -- "$cur") )
    return 0
  fi
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_view_run() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-p --param --json -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

_postman_dataset_view_create() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-n --name -q --query --id -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
  _postman_filematch '!*.@(json)' "$cur"
}

_postman_dataset_view_delete() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-h --help" -- "$cur") )
    return 0
  fi
}

_postman_dataset_view_update() {
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "-n --name -q --query -h --help" -- "$cur") )
    return 0
  fi
  case "$prev" in
  esac
}

complete -F _postman postman
