# Fish completion for Postman CLI (postman v1.39.0)
# Auto-generated by scripts/generate.mjs — DO NOT EDIT
# Source: spec/commands.json
# https://github.com/yokawasa/postman-cli-completion

function __postman_no_subcommand
    not __fish_seen_subcommand_from login logout collection api runner spec monitor workspace performance flows fl request sdk mock application app simulate context search webhook
end

function __postman_using_subcommand
    set -l parent $argv[1]
    set -l leaves $argv[2..]
    __fish_seen_subcommand_from $parent
    and not __fish_seen_subcommand_from $leaves
end

# ---------- Global flags ----------
complete -c postman -n __postman_no_subcommand -s v -l version -d 'output the version number'
complete -c postman -n __postman_no_subcommand -l silent -d 'Silences all terminal output'
complete -c postman -n __postman_no_subcommand -l color -d 'Enable/Disable colored output (auto|on|off) (default: "auto")' -x -a 'auto on off'
complete -c postman -n __postman_no_subcommand -s h -l help -d 'display help for command'

# ---------- Top-level commands ----------
complete -c postman -n __postman_no_subcommand -a login -d 'Authenticate with Postman to access your resources.'
complete -c postman -n __postman_no_subcommand -a logout -d 'Delete the stored Postman API key.'
complete -c postman -n __postman_no_subcommand -a collection -d 'Run and test your Postman collections directly from the command line.'
complete -c postman -n __postman_no_subcommand -a api -d 'Publish and test your APIs directly from the command line'
complete -c postman -n __postman_no_subcommand -a runner -d 'Run runners on your own environments for monitoring your APIs'
complete -c postman -n __postman_no_subcommand -a spec -d 'Lint and validate Specifications from the command line'
complete -c postman -n __postman_no_subcommand -a monitor -d 'Invoke a monitor run and display results'
complete -c postman -n __postman_no_subcommand -a workspace -d 'Manage workspace resources.'
complete -c postman -n __postman_no_subcommand -a performance -d 'Manage performance tests on your collections.'
complete -c postman -n __postman_no_subcommand -a flows -d 'Manage and interact with flows.'
complete -c postman -n __postman_no_subcommand -a fl -d 'Alias for flows'
complete -c postman -n __postman_no_subcommand -a request -d 'Send HTTP requests from the command line with full Postman capabilities including authentication, environment variables, assertions, retries, and detailed output control.'
complete -c postman -n __postman_no_subcommand -a sdk -d 'Generate and manage your SDKs directly from the command line.'
complete -c postman -n __postman_no_subcommand -a mock -d 'Run and manage local Postman mock servers.'
complete -c postman -n __postman_no_subcommand -a application -d 'Application-level commands: initialise config and run tests.'
complete -c postman -n __postman_no_subcommand -a app -d 'Alias for application'
complete -c postman -n __postman_no_subcommand -a simulate -d 'Start mock servers with simulated failure scenarios.'
complete -c postman -n __postman_no_subcommand -a context -d '[Beta] Get API context for AI coding agents directly from the command line.'
complete -c postman -n __postman_no_subcommand -a search -d 'Search for Postman element types (requests, collections, workspaces, and more).'
complete -c postman -n __postman_no_subcommand -a webhook -d 'Create and manage Postman webhooks.'

# ---------- login ----------
complete -c postman -n '__fish_seen_subcommand_from login' -l alias -d 'Specify the alias of the API key to fetch your resources using it. (This option is discontinued and will be removed in a future release.)' -x
complete -c postman -n '__fish_seen_subcommand_from login' -l with-api-key -d 'Specify the API key directly.' -x
complete -c postman -n '__fish_seen_subcommand_from login' -l region -d 'Specify the region for authentication. Use "eu" for EU region.' -x -a 'us eu'
complete -c postman -n '__fish_seen_subcommand_from login' -l verbose -d 'Show detailed error information'
complete -c postman -n '__fish_seen_subcommand_from login' -s h -l help -d 'display help for command'

# ---------- logout ----------
complete -c postman -n '__fish_seen_subcommand_from logout' -l alias -d 'Specify the alias of the API key to fetch your resources using it. (This option is discontinued and will be removed in a future release.)' -x
complete -c postman -n '__fish_seen_subcommand_from logout' -s h -l help -d 'display help for command'

# ---------- collection ----------
complete -c postman -n '__postman_using_subcommand collection migrate lint ai-readiness run' -a migrate -d 'Migrate a v2.1 collection to the v3 format'
complete -c postman -n '__postman_using_subcommand collection migrate lint ai-readiness run' -a lint -d 'Run linting on a local v3 collection at the given file or directory path.'
complete -c postman -n '__postman_using_subcommand collection migrate lint ai-readiness run' -a ai-readiness -d 'Score a Postman collection for AI readiness by ID, local file path, or local-mode directory.'
complete -c postman -n '__postman_using_subcommand collection migrate lint ai-readiness run' -a run -d 'Initiate a Postman collection run from a given ID or path.'
complete -c postman -n '__fish_seen_subcommand_from collection' -s h -l help -d 'display help for command'
# ---------- collection migrate ----------
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from migrate' -s o -l output -d 'Output directory (default: ./<collection-name>)' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from migrate' -s h -l help -d 'display help for command'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from migrate' -r -k -a '(__fish_complete_suffix .json)'
# ---------- collection lint ----------
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from lint' -s f -l fail-severity -d 'Exit with failure if diagnostics at this level or above are present. [choices: "error", "warning"] (default: "error")' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from lint' -s r -l reporter -d 'Output format: cli (human-readable) or json. (default: "cli")' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from lint' -s h -l help -d 'display help for command'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from lint' -r -k -a '(__fish_complete_suffix .json)'
# ---------- collection ai-readiness ----------
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from ai-readiness' -s o -l output -d 'Output format for the results. [choices: "cli", "json"]' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from ai-readiness' -l min-score -d 'Exit with a non-zero code if the overall score is below this threshold (0-100).' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from ai-readiness' -s h -l help -d 'display help for command'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from ai-readiness' -r -k -a '(__fish_complete_suffix .json)'
# ---------- collection run ----------
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s e -l environment -d 'Specify an Id or path to a Postman Environment' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s g -l globals -d 'Specify an Id or path to a file containing Postman Globals' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s r -l reporters -d 'Specify the reporters to use for the run: cli,json,junit,html. For multiple reporters, provide their names as a comma-separated list (E.g., -r cli,json) (default: ["cli"])' -x -a 'cli json junit html'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-json-structure -d '[Optional] Generate JSON report using the Newman schema. By default, JSON reports use the native structure of Postman CLI.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s n -l iteration-count -d 'Define the number of iterations to run' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s d -l iteration-data -d 'Specify a data file to use for iterations (either JSON or CSV)' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s i -d 'Specify the request/folder id, name, or path to run from the collection. Use a path (e.g. "FolderName/RequestName") to disambiguate items with the same name. Can be specified multiple times to run multiple items (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l global-var -d 'Allows the specification of global variables via the command line, in a key=value format' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l env-var -d 'Allows the specification of environment variables via the command line, in a key=value format (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l integration-id -d 'Specify the integration id for the report. (Only supported in the US region)' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l postman-api-key -d 'API Key used to load the resources from the Postman API (Only supported in the US region, use \'postman login --region\' to authenticate instead)' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l alias -d 'Specify the alias of the API key to fetch remote resources using it.' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l bail -d 'Specify whether or not to gracefully stop a collection run on encountering an error and whether to end the run with an error based on the optional modifier' -x -a 'folder failure'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l ignore-redirects -d 'Prevents Postman CLI from automatically following 3XX redirect responses'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s x -l suppress-exit-code -d 'Specify whether or not to override the default exit code for the current run'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l silent -d 'Prevents Postman CLI from showing output to CLI'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l disable-unicode -d 'Forces Unicode compliant symbols to be replaced by their plain text equivalents'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l delay-request -d 'Specify the extent of delay between requests (milliseconds) (default: 0)' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l timeout -d 'Specify a timeout for collection run (milliseconds) (default: 0)' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l timeout-request -d 'Specify a timeout for requests (milliseconds) (default: 0)' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l timeout-script -d 'Specify a timeout for scripts (milliseconds) (default: 0)' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l working-dir -d 'Specify the path to the working directory' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l no-insecure-file-read -d 'Prevents reading the files situated outside of the working directory'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s k -l insecure -d 'Disables SSL validations'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l ssl-client-cert-list -d 'Specify the path to a client certificates configurations (JSON)' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l ssl-client-cert -d 'Specify the path to a client certificate (PEM)' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l ssl-client-key -d 'Specify the path to a client certificate private key' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l ssl-client-passphrase -d 'Specify the client certificate passphrase (for protected key)' -x
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l ssl-extra-ca-certs -d 'Specify additionally trusted CA certificates (PEM)' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l cookie-jar -d 'Specify the path to a custom cookie jar (serialized tough-cookie JSON)' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l export-cookie-jar -d 'Exports the cookie jar to a file after completing the run' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l verbose -d 'Show detailed information of collection run and each request sent'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l mock -d 'Start a mock server from manifest (.json) file' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l simulate -d 'Start mock servers with fault-injection scenarios from a .sim.yaml file' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -s h -l help -d 'display help for command'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-json-export -d 'Path to save the report for the given reporter.' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-junit-export -d 'Path to save the report for the given reporter.' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-html-export -d 'Path to save the report for the given reporter.' -r
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-json-omitRequestBodies -d 'Remove all request bodies from the report.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-html-omitRequestBodies -d 'Remove all request bodies from the report.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-json-omitResponseBodies -d 'Remove all response bodies from the report.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-html-omitResponseBodies -d 'Remove all response bodies from the report.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-json-omitHeaders -d 'Remove all request and response headers from the report.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-html-omitHeaders -d 'Remove all request and response headers from the report.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-json-omitAllHeadersAndBody -d 'Remove all request/response headers and bodies from the report.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -l reporter-html-omitAllHeadersAndBody -d 'Remove all request/response headers and bodies from the report.'
complete -c postman -n '__fish_seen_subcommand_from collection; and __fish_seen_subcommand_from run' -r -k -a '(__fish_complete_suffix .json)'

# ---------- api ----------
complete -c postman -n '__postman_using_subcommand api lint publish' -a lint -d 'Run linting on the schema of the given API ID or local file in the given path. If [api] is not provided we will run the linting on the schema present in the .postman config file'
complete -c postman -n '__postman_using_subcommand api lint publish' -a publish -d 'Publish a version of an API for the given apiId. All entities added to the API will be published by default. User can choose which entities to publish by using additional options.'
complete -c postman -n '__fish_seen_subcommand_from api' -s h -l help -d 'display help for command'
# ---------- api lint ----------
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from lint' -l integration-id -d 'Specify the integration ID for the report.' -x
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from lint' -s f -l fail-severity -d 'Results of this level or above will trigger a failure exit code. [choices: "error", "warn", "info", "hint"] (default: "ERROR")' -x
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from lint' -s x -l suppress-exit-code -d 'Specify whether or not to override the default exit code for the current run'
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from lint' -s h -l help -d 'display help for command'
# ---------- api publish ----------
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from publish' -l name -d 'Specify the name of the version to publish.' -x
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from publish' -l release-notes -d 'Specify release notes for the version to publish.' -x
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from publish' -l collections -d 'Specify the collections to publish. If API is connected to a repository, provide file path instead of IDs.' -r
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from publish' -l api-definition -d 'Specify the API Definition to publish. If API is connected to a repository, provide schema root file path. Note that some repository connections utilize a schema directory path; for such APIs, provide schema directory path instead of file path.' -x
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from publish' -l do-not-poll -d 'Specify whether or not to poll for completion status of the publish action.'
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from publish' -s x -l suppress-exit-code -d 'Specify whether or not to override the default exit code for the current run.'
complete -c postman -n '__fish_seen_subcommand_from api; and __fish_seen_subcommand_from publish' -s h -l help -d 'display help for command'

# ---------- runner ----------
complete -c postman -n '__postman_using_subcommand runner start' -a start -d 'Start a runner'
complete -c postman -n '__fish_seen_subcommand_from runner' -s h -l help -d 'display help for command'
# ---------- runner start ----------
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l id -d 'The ID of the runner to execute' -x
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l key -d 'The secret key for the runner' -r
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l region -d 'Specify the region for the runner. Use "eu" for EU region.' -x
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l proxy -d 'External proxy URL (e.g., http://proxy.com or http://proxy.com:8080)' -x
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l egress-proxy -d 'Enable built-in egress proxy'
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l egress-proxy-authz-url -d 'Custom egress proxy authorization service base URL' -x
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l ssl-extra-ca-certs -d 'Additional trusted CA certificates (PEM file, can contain multiple certs)' -r
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l metrics -d 'Enable the metrics server for health checks'
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -l metrics-port -d 'Port for the metrics server (default: "9090")' -x
complete -c postman -n '__fish_seen_subcommand_from runner; and __fish_seen_subcommand_from start' -s h -l help -d 'display help for command'

# ---------- spec ----------
complete -c postman -n '__postman_using_subcommand spec lint ai-readiness' -a lint -d 'Run linting on the given specification by ID or local file path.'
complete -c postman -n '__postman_using_subcommand spec lint ai-readiness' -a ai-readiness -d 'Score an OpenAPI specification for AI readiness by ID or local file path.'
complete -c postman -n '__fish_seen_subcommand_from spec' -s h -l help -d 'display help for command'
# ---------- spec lint ----------
complete -c postman -n '__fish_seen_subcommand_from spec; and __fish_seen_subcommand_from lint' -s f -l fail-severity -d 'Results of this level or above will trigger a failure exit code. [choices: "error", "warning", "info", "hint"] (default: "ERROR")' -x
complete -c postman -n '__fish_seen_subcommand_from spec; and __fish_seen_subcommand_from lint' -s o -l output -d 'Output format for the results. [choices: "json", "csv"]' -x
complete -c postman -n '__fish_seen_subcommand_from spec; and __fish_seen_subcommand_from lint' -l workspace-id -d 'The workspace ID to use for fetching governance rulesets.' -x
complete -c postman -n '__fish_seen_subcommand_from spec; and __fish_seen_subcommand_from lint' -s h -l help -d 'display help for command'
# ---------- spec ai-readiness ----------
complete -c postman -n '__fish_seen_subcommand_from spec; and __fish_seen_subcommand_from ai-readiness' -s o -l output -d 'Output format for the results. [choices: "cli", "json"]' -x
complete -c postman -n '__fish_seen_subcommand_from spec; and __fish_seen_subcommand_from ai-readiness' -l min-score -d 'Exit with a non-zero code if the overall score is below this threshold (0-100).' -x
complete -c postman -n '__fish_seen_subcommand_from spec; and __fish_seen_subcommand_from ai-readiness' -s h -l help -d 'display help for command'

# ---------- monitor ----------
complete -c postman -n '__postman_using_subcommand monitor run' -a run -d 'Invoke a monitor run and display results.'
complete -c postman -n '__fish_seen_subcommand_from monitor' -s h -l help -d 'display help for command'
# ---------- monitor run ----------
complete -c postman -n '__fish_seen_subcommand_from monitor; and __fish_seen_subcommand_from run' -s x -l suppress-exit-code -d 'Specify whether or not to override the default exit code for the current run'
complete -c postman -n '__fish_seen_subcommand_from monitor; and __fish_seen_subcommand_from run' -s t -l timeout -d 'Maximum wait time for run completion in milliseconds (default: 15 minutes) (default: 900000)' -x
complete -c postman -n '__fish_seen_subcommand_from monitor; and __fish_seen_subcommand_from run' -s h -l help -d 'display help for command'

# ---------- workspace ----------
complete -c postman -n '__postman_using_subcommand workspace prepare push' -a prepare -d 'Prepare local collections and environments for push by validating and regenerating IDs if needed.'
complete -c postman -n '__postman_using_subcommand workspace prepare push' -a push -d 'Push local collection, environment, and specification changes to Postman workspace.'
complete -c postman -n '__fish_seen_subcommand_from workspace' -s h -l help -d 'display help for command'
# ---------- workspace prepare ----------
complete -c postman -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from prepare' -l collections-dir -d 'Path to the collections directory (default: "postman/collections")' -x
complete -c postman -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from prepare' -l environments-dir -d 'Path to the environments directory (default: "postman/environments")' -x
complete -c postman -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from prepare' -s h -l help -d 'display help for command'
# ---------- workspace push ----------
complete -c postman -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from push' -l collections-dir -d 'Path to the collections directory (default: "postman/collections")' -x
complete -c postman -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from push' -l environments-dir -d 'Path to the environments directory (default: "postman/environments")' -x
complete -c postman -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from push' -l no-prepare -d 'Skip ID validation and auto-fix before pushing'
complete -c postman -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from push' -s y -l yes -d 'Skip all confirmation prompts'
complete -c postman -n '__fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from push' -s h -l help -d 'display help for command'

# ---------- performance ----------
complete -c postman -n '__postman_using_subcommand performance run' -a run -d 'Run a performance test on a collection'
complete -c postman -n '__fish_seen_subcommand_from performance' -s h -l help -d 'display help for command'
# ---------- performance run ----------
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -s e -l environment -d 'Specify an Id to a Postman Environment' -x
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -s g -l globals -d 'Specify an Id to a Postman Globals' -x
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -l vu-count -d 'Number of virtual users (default: 20)' -x
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -s d -l duration -d 'Duration of the performance test in minutes (default: 10)' -x
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -s p -l load-profile -d 'Load profile type: fixed, ramp-up, spike, peak (default: "ramp-up")' -x
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -l data-file -d 'Path to a JSON or CSV data file to use with the collection' -r
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -l postman-api-key -d 'API Key used to load the resources from the Postman API (Only supported in the US region, use \'postman login --region\' to authenticate instead)' -x
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -l pass-if -d 'Pass condition in format: function(metric, value). Functions: less_than, greater_than, less_than_eq, greater_than_eq. Metrics: avg, p90, p95, p99, error_rate, rps. Example: less_than(p95, 500) or less_than(error_rate, 5)' -x
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -s h -l help -d 'display help for command'
complete -c postman -n '__fish_seen_subcommand_from performance; and __fish_seen_subcommand_from run' -r -k -a '(__fish_complete_suffix .json)'

# ---------- flows ----------
complete -c postman -n '__postman_using_subcommand flows list trigger deploy run update list-runs get-run' -a list -d 'List all flows'
complete -c postman -n '__postman_using_subcommand flows list trigger deploy run update list-runs get-run' -a trigger -d 'Trigger a deployed flow'
complete -c postman -n '__postman_using_subcommand flows list trigger deploy run update list-runs get-run' -a deploy -d 'Deploy a flow (required to trigger it)'
complete -c postman -n '__postman_using_subcommand flows list trigger deploy run update list-runs get-run' -a run -d 'Run a single flow from a file (e.g. ./path/to/flow.json)'
complete -c postman -n '__postman_using_subcommand flows list trigger deploy run update list-runs get-run' -a update -d 'Update settings for a deployed flow'
complete -c postman -n '__postman_using_subcommand flows list trigger deploy run update list-runs get-run' -a list-runs -d 'List run history for a deployed flow'
complete -c postman -n '__postman_using_subcommand flows list trigger deploy run update list-runs get-run' -a get-run -d 'Analyze a specific flow run'
complete -c postman -n '__fish_seen_subcommand_from flows' -s h -l help -d 'display help for command'
# ---------- flows list ----------
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list' -s w -l workspace -d 'Specify the workspace ID to list flows from' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list' -s p -l paginate -d 'Paginates the list of flows'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list' -s f -l filter -d 'Filter flows by name. Pattern may be a regex, or a name prefix.' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list' -s s -l sort -d 'Sort flows by criteria: "name" or "updated" (default: updated) (default: "updated")' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list' -l verbose -d 'Verbose output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list' -l debug -d 'Debug output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list' -l json -d 'JSON output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list' -s h -l help -d 'display help for command'
# ---------- flows trigger ----------
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -s i -l input -d 'Set key=value pairs in the trigger payload (e.g. --input foo=bar --input baz=qux) (default: [])' -r
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -s f -l input-file -d 'Set payload values from JSON files (e.g. --input-file ./inputs.json --input-file ./config.json) (default: [])' -r
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -s q -l query -d 'Set query parameters as key=value pairs (e.g. --query foo=bar --query baz=qux) (default: [])' -r
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -l headers -d 'Set custom headers as key=value pairs (e.g. --headers X-API-Key=12345 --headers User-Agent=MyApp) (default: [])' -r
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -s n -l dry-run -d 'Show the flow requestURL and payload that would be sent without making the actual request (default: false)'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -l show-secrets -d 'Show actual authentication tokens in dry-run output (otherwise secrets are masked) (default: false)'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -s r -l result -d 'Show only the response body (default: false)'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -s s -l scenario -d 'Use a named scenario from the flow definition to construct the input payload, headers, and query parameters (overridden by --headers/--query)' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -l verbose -d 'Verbose output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -l debug -d 'Debug output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -l json -d 'JSON output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from trigger' -s h -l help -d 'display help for command'
# ---------- flows deploy ----------
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from deploy' -s p -l path -d 'Specify the URL path for the trigger' -r
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from deploy' -s t -l timeout -d 'Specify the HTTP session timeout (5000ms to 60000ms) (default: "10000ms")' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from deploy' -s a -l auth -d 'Enable authentication for the trigger (default: false)'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from deploy' -l verbose -d 'Verbose output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from deploy' -l debug -d 'Debug output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from deploy' -l json -d 'JSON output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from deploy' -s h -l help -d 'display help for command'
# ---------- flows run ----------
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -s i -l input -d 'Set flow inputs as key=value pairs (e.g. --input foo=bar --input baz=qux) (default: [])' -r
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -s f -l input-file -d 'Set flow inputs from JSON files (e.g. --input-file ./inputs.json --input-file ./config.json) (default: [])' -r
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -s s -l scenario -d 'Use a pre-built scenario as flow inputs (by scenario name). Can be combined with --input and --input-file to override values.' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -s e -l environment -d 'Specify a path to a Postman Environment file (JSON or YAML)' -r
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l working-dir -d 'Specify the path to the working directory' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l verbose -d 'Show detailed information of flow run and each request (method, URL, assertions)'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l no-truncate -d 'Show full output without truncating long values'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l output -d 'Save execution result to a file (supported: json)' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l reporters -d 'Save a test results report to a file (supported: html)' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -s x -l suppress-exit-code -d 'Specify whether or not to override the default exit code for the current run'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l workspace -d 'Workspace ID required for flows that contain connector blocks. Find it in the Postman app URL: https://postman.com/workspace/<workspaceId>' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l verbose -d 'Verbose output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l debug -d 'Debug output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -l json -d 'JSON output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -s h -l help -d 'display help for command'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from run' -r -k -a '(__fish_complete_suffix .json)'
# ---------- flows update ----------
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from update' -s t -l trigger -d 'Enable or disable the flow trigger' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from update' -s a -l auth -d 'Enable or disable authentication for the flow trigger' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from update' -l verbose -d 'Verbose output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from update' -l debug -d 'Debug output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from update' -l json -d 'JSON output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from update' -s h -l help -d 'display help for command'
# ---------- flows list-runs ----------
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list-runs' -s w -l workspace -d 'Specify the workspace ID' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list-runs' -s f -l flow -d 'Filter sessions by flow ID' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list-runs' -s r -l range -d 'Time range to list runs (e.g. 30m, 2h, 3d) (default: "1h")' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list-runs' -l verbose -d 'Verbose output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list-runs' -l debug -d 'Debug output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list-runs' -l json -d 'JSON output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from list-runs' -s h -l help -d 'display help for command'
# ---------- flows get-run ----------
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from get-run' -s r -l run-id -d 'Specify the run ID to analyze' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from get-run' -s l -l logs -d 'Show detailed event log (default: false)'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from get-run' -l filter -d 'Filter event log by block ID prefix (can be specified multiple times) (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from get-run' -l verbose -d 'Verbose output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from get-run' -l debug -d 'Debug output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from get-run' -l json -d 'JSON output'
complete -c postman -n '__fish_seen_subcommand_from flows; and __fish_seen_subcommand_from get-run' -s h -l help -d 'display help for command'

# ---------- request ----------
complete -c postman -n '__fish_seen_subcommand_from request' -s H -l header -d 'Add HTTP header in key:value format. Can be used multiple times. Example: -H "Content-Type:application/json" -H "X-API-Key:abc123" (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from request' -s d -l body -d 'Request body content. Supports: inline string, @filepath for file content, or "-" for stdin. Example: --body \'{"name":"John"}\' or --body @data.json' -x
complete -c postman -n '__fish_seen_subcommand_from request' -s f -l form -d 'Add multipart/form-data field in key=value format. Can be used multiple times. For file uploads use key=@filepath. Example: -f "name=John" -f "avatar=@photo.jpg" (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from request' -s e -l environment -d 'Load Postman Environment by UUID or file path. Variables in URL, headers, and body will be resolved. Example: -e dev.postman_environment.json' -r
complete -c postman -n '__fish_seen_subcommand_from request' -l timeout -d 'Request timeout in milliseconds. Request will fail if no response within this time. (default: 300000)' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l redirects-ignore -d 'Prevents Postman CLI from automatically following 3XX redirect responses. By default, redirects are followed.'
complete -c postman -n '__fish_seen_subcommand_from request' -l redirects-max -d 'Maximum number of redirects to follow. Default is unlimited. Useful for preventing redirect loops.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l redirects-follow-method -d 'Preserves the original HTTP method when following redirects. By default, redirects are followed with GET method.'
complete -c postman -n '__fish_seen_subcommand_from request' -l redirects-remove-referrer -d 'Removes the Referer header when following redirects. By default, Referer header is sent with redirects.'
complete -c postman -n '__fish_seen_subcommand_from request' -l retry -d 'Number of retry attempts for failed requests (4xx, 5xx, network errors). Useful for flaky endpoints or rate-limited APIs. (default: 0)' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l retry-delay -d 'Delay between retry attempts in milliseconds. (default: 1000)' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l script-pre-request -d 'Add JavaScript script to run before the request. Can be inline JS or @filepath to load from file. Scripts have access to pm.* APIs. Example: --script-pre-request "pm.environment.set(\'timestamp\', Date.now());" or --script-pre-request @setup.js' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l script-post-request -d 'Add JavaScript script to run after the request. Can be inline JS or @filepath to load from file. Scripts have access to pm.* APIs. Example: --script-post-request "console.log(pm.response.json());" or --script-post-request @validate.js' -x
complete -c postman -n '__fish_seen_subcommand_from request' -s o -l output -d 'Save complete response to JSON file.Useful for debugging or further processing.' -r
complete -c postman -n '__fish_seen_subcommand_from request' -l verbose -d 'Show detailed request and response information including headers, body, and metadata.'
complete -c postman -n '__fish_seen_subcommand_from request' -l response-only -d 'suppress all output except response body. Useful for piping to other commands.'
complete -c postman -n '__fish_seen_subcommand_from request' -l debug -d 'Debug mode: show detailed execution information including retry attempts, redirects, and timing breakdowns.'
complete -c postman -n '__fish_seen_subcommand_from request' -s h -l help -d 'display help for command'
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-basic-username -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-basic-password -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-bearer-token -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-digest-username -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-digest-password -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-oauth1-consumerKey -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-oauth1-consumerSecret -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-oauth1-token -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-oauth1-tokenSecret -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-oauth2-accessToken -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-oauth2-tokenType -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-hawk-authId -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-hawk-authKey -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-hawk-algorithm -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-aws-accessKey -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-aws-secretKey -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-aws-region -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-aws-service -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-aws-sessionToken -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-ntlm-username -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-ntlm-password -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-ntlm-domain -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-ntlm-workstation -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-apikey-key -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-apikey-value -d 'Supply authentication parameters dynamically.' -x
complete -c postman -n '__fish_seen_subcommand_from request' -l auth-apikey-in -d 'Supply authentication parameters dynamically.' -x

# ---------- sdk ----------
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a init -d 'Create or update .postman/config.json with an SDK configuration stub.'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a generate -d 'Generate a new SDK from a Postman collection or specification.'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a build -d 'Alias for generate'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a track -d 'Enable change tracking for a generated SDK. Adds file hashes to .manifest.json so that the next `sdk generate` can detect your edits and preserve them via 3-way merge.'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a list -d 'List SDK builds for a collection, extensible collection, or specification.'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a ls -d 'Alias for list'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a fetch -d 'Download SDKs from a build by its ID.'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a get -d 'Alias for fetch'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a connect -d 'Connect a collection or specification to a GitHub repository for automatic SDK pull requests'
complete -c postman -n '__postman_using_subcommand sdk init generate build track list ls fetch get connect connections' -a connections -d 'Manage GitHub connections that drive automatic SDK pull requests'
complete -c postman -n '__fish_seen_subcommand_from sdk' -s h -l help -d 'display help for command'
# ---------- sdk init ----------
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from init' -s y -l yes -d 'Skip prompts and overwrite existing sdk config'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from init' -s h -l help -d 'display help for command'
# ---------- sdk generate ----------
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -s l -l language -d 'Target language(s) for SDK generation. Specify one or more languages. [choices: "typescript", "python", "java", "go", "csharp", "php", "ruby", "cli", "kotlin", "rust"]' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l all -d 'Generate SDKs for all supported languages'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -s o -l output-dir -d 'Directory where the generated SDK will be saved (default: "./sdks")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l name -d 'Name for the generated SDK package' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l sdk-version -d 'Version number for the generated SDK' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l config -d 'Path to SDK generation config file (JSON). If not specified, will look for .postman/config.json (sdk key).' -r
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -s y -l yes -d 'Skip all confirmation prompts and overwrite existing files'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l overwrite -d 'Overwrite existing files without confirmation'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l verbose -d 'Show detailed generation progress and logs'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l log-level -d 'Set build log detail level. "warn" (default) shows errors/warnings inline and collapses info notes; "info" expands all log entries (default: "warn")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l no-track-changes -d 'Disable change tracking. By default, file hashes are written into .manifest.json to enable edit detection on the next regeneration.'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l no-merge -d 'Skip custom code merge even if user edits are detected. Forces a fresh generation.'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l conflict-strategy -d 'Strategy for handling merge conflicts: "mark" inserts conflict markers (default), "ours" keeps user edits, "theirs" keeps generated code' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -l no-emit -d 'Skip downloading and saving SDK artifacts to disk. Useful in CI when the build only needs to trigger server-side pull requests.'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from generate' -s h -l help -d 'display help for command'
# ---------- sdk track ----------
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from track' -s l -l language -d 'Language(s) to track. [choices: "typescript", "python", "java", "go", "csharp", "php", "ruby", "cli", "kotlin", "rust"]' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from track' -s o -l output-dir -d 'Base directory containing generated SDKs (default: "./sdks")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from track' -s h -l help -d 'display help for command'
# ---------- sdk list ----------
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from list' -s s -l status -d 'Filter builds by status (case-insensitive) [choices: in-progress, success, failure]' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from list' -s o -l output -d 'Output format [choices: "json", "table"] (default: "table")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from list' -l log-level -d 'Set build log detail level. "warn" (default) shows errors/warnings inline and collapses info notes; "info" expands all log entries (default: "warn")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from list' -s h -l help -d 'display help for command'
# ---------- sdk fetch ----------
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from fetch' -s o -l output-dir -d 'Directory to save the downloaded SDK(s) (default: "./sdks")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from fetch' -s l -l language -d 'Download only the specified language (e.g., typescript, python)' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from fetch' -l overwrite -d 'Overwrite existing files without confirmation'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from fetch' -l verbose -d 'Show detailed download progress'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from fetch' -l log-level -d 'Set build log detail level. "warn" (default) shows errors/warnings inline and collapses info notes; "info" expands all log entries (default: "warn")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from fetch' -s h -l help -d 'display help for command'
# ---------- sdk connect ----------
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -s l -l language -d 'SDK language (required) [choices: typescript, python, java, go, csharp, php, ruby, cli, kotlin, rust]' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -s r -l repo -d 'GitHub repository in <owner>/<name> form (alternative to --repo-owner + --repo-name)' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -l repo-owner -d 'GitHub repository owner (user or org)' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -l repo-name -d 'GitHub repository name' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -s b -l branch -d 'Target branch for SDK pull requests (default: "main")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -l push-to-base -d 'Push SDK updates directly to the base branch instead of opening a pull request (default: false)'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -l enable-npm-publishing -d 'Inject a GitHub Actions workflow that publishes to npm on merge (TypeScript only) (default: false)'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -l auth-provider -d 'OAuth provider used by the server when pushing (choices: githubapp, github) (default: "githubapp")' -x
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -l verbose -d 'Show extra logging'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connect' -s h -l help -d 'display help for command'
# ---------- sdk connections ----------
complete -c postman -n '__postman_using_subcommand connections list ls delete rm' -a list -d 'List GitHub connections for a collection or specification'
complete -c postman -n '__postman_using_subcommand connections list ls delete rm' -a ls -d 'Alias for list'
complete -c postman -n '__postman_using_subcommand connections list ls delete rm' -a delete -d 'Delete a GitHub connection for a collection or specification'
complete -c postman -n '__postman_using_subcommand connections list ls delete rm' -a rm -d 'Alias for delete'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connections' -s h -l help -d 'display help for command'
# ---------- sdk connections list ----------
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connections; and __fish_seen_subcommand_from list' -l refresh -d 'Refresh PR statuses from GitHub before listing (slower) (default: false)'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connections; and __fish_seen_subcommand_from list' -l json -d 'Output raw JSON instead of formatted text (default: false)'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connections; and __fish_seen_subcommand_from list' -l verbose -d 'Show extra logging'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connections; and __fish_seen_subcommand_from list' -s h -l help -d 'display help for command'
# ---------- sdk connections delete ----------
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connections; and __fish_seen_subcommand_from delete' -s y -l yes -d 'Skip the confirmation prompt (default: false)'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connections; and __fish_seen_subcommand_from delete' -l verbose -d 'Show extra logging'
complete -c postman -n '__fish_seen_subcommand_from sdk; and __fish_seen_subcommand_from connections; and __fish_seen_subcommand_from delete' -s h -l help -d 'display help for command'

# ---------- mock ----------
complete -c postman -n '__postman_using_subcommand mock run' -a run -d 'Start a local mock server given a manifest file.'
complete -c postman -n '__fish_seen_subcommand_from mock' -s h -l help -d 'display help for command'
# ---------- mock run ----------
complete -c postman -n '__fish_seen_subcommand_from mock; and __fish_seen_subcommand_from run' -s e -l environment -d 'Path to an environment file (JSON or YAML) for pm.environment' -r
complete -c postman -n '__fish_seen_subcommand_from mock; and __fish_seen_subcommand_from run' -s g -l globals -d 'Path to a globals file (JSON or YAML) for pm.globals' -r
complete -c postman -n '__fish_seen_subcommand_from mock; and __fish_seen_subcommand_from run' -s h -l help -d 'display help for command'

# ---------- application ----------
complete -c postman -n '__postman_using_subcommand application init test' -a init -d 'Initialise a postman.config.cjs file with target collections, environment, and test command.'
complete -c postman -n '__postman_using_subcommand application init test' -a test -d 'Run a command first (primary task), then match captured traffic against Postman collections and run assertions.'
complete -c postman -n '__fish_seen_subcommand_from application' -s h -l help -d 'display help for command'
# ---------- application init ----------
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from init' -l target-collection -d 'Collection name or path for the default target (repeatable) (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from init' -l target-environment -d 'Environment name or path for the default target (last value wins) (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from init' -l filter-urlpatterns -d 'Comma-separated URL patterns to exclude from captured traffic (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from init' -l filter-methods -d 'Comma-separated HTTP methods to exclude from captured traffic (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from init' -l filter-headers -d 'Comma-separated request header filters in header=value form (default: [])' -x
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from init' -l command -d 'Command to run your tests (e.g. "npx playwright test")' -x
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from init' -s h -l help -d 'display help for command'
# ---------- application test ----------
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l target -d 'Select a target from postman.config.js targets block (default: "default")' -x
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l target-collection -d 'Collection override for the selected target (repeatable) (default: [])' -r
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l target-environment -d 'Environment override for the selected target (last value wins) (default: [])' -r
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l command -d 'Command to run first (primary task). Overrides config.' -x
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l network-log -d 'Directory to scan for captured artifacts, or a direct path to a Playwright JSON report / NDJSON capture file. When a directory is given, recursively discovers `*.json` Playwright reports plus their `trace.zip` attachments, and `network-capture-*.ndjson` at the top level. By default, scans Playwright config `outputDir`, test-results/, then pm-results/.' -r
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l capture-only -d 'Skip collection matching and tests; capture traffic and save a V3 collection organised by host'
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l output -d 'Output directory for captured collection (default: pm-results/captured/; used with --capture-only)' -r
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l force -d 'Overwrite the output directory if it exists and is not empty (used with --capture-only)'
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l report-events -d 'Send application test run results and analytics to Postman'
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -l verbose -d 'Show detailed per-request matching, sandbox errors, and debug information'
complete -c postman -n '__fish_seen_subcommand_from application; and __fish_seen_subcommand_from test' -s h -l help -d 'display help for command'

# ---------- simulate ----------
complete -c postman -n '__postman_using_subcommand simulate run' -a run -d 'Start mocks with fault-injection scenarios defined in a .sim.yaml file'
complete -c postman -n '__fish_seen_subcommand_from simulate' -s h -l help -d 'display help for command'
# ---------- simulate run ----------
complete -c postman -n '__fish_seen_subcommand_from simulate; and __fish_seen_subcommand_from run' -s h -l help -d 'display help for command'
complete -c postman -n '__fish_seen_subcommand_from simulate; and __fish_seen_subcommand_from run' -r -k -a '(__fish_complete_suffix .json)'

# ---------- context ----------
complete -c postman -n '__postman_using_subcommand context instructions collection request folder response workspace environment' -a instructions -d 'Get agent instructions for using Postman Context with AI coding agents.'
complete -c postman -n '__postman_using_subcommand context instructions collection request folder response workspace environment' -a collection -d 'Collection commands'
complete -c postman -n '__postman_using_subcommand context instructions collection request folder response workspace environment' -a request -d 'Request commands'
complete -c postman -n '__postman_using_subcommand context instructions collection request folder response workspace environment' -a folder -d 'Folder commands'
complete -c postman -n '__postman_using_subcommand context instructions collection request folder response workspace environment' -a response -d 'Response commands'
complete -c postman -n '__postman_using_subcommand context instructions collection request folder response workspace environment' -a workspace -d 'Workspace commands'
complete -c postman -n '__postman_using_subcommand context instructions collection request folder response workspace environment' -a environment -d 'Environment commands'
complete -c postman -n '__fish_seen_subcommand_from context' -s h -l help -d 'display help for command'
# ---------- context instructions ----------
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from instructions' -s h -l help -d 'display help for command'
# ---------- context collection ----------
complete -c postman -n '__postman_using_subcommand collection get' -a get -d 'Get a collection\'s metadata and a map of its folders and requests. Returns collection info (name, description, variables, auth) plus a recursive tree of folders and requests.'
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from collection' -s h -l help -d 'display help for command'
# ---------- context collection get ----------
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from collection; and __fish_seen_subcommand_from get' -s c -l collection-id -d 'Collection ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from collection; and __fish_seen_subcommand_from get' -s h -l help -d 'display help for command'
# ---------- context request ----------
complete -c postman -n '__postman_using_subcommand request get context' -a get -d 'Get a request from a collection'
complete -c postman -n '__postman_using_subcommand request get context' -a context -d 'Fetch all context about a request and return it as a Markdown document.'
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from request' -s h -l help -d 'display help for command'
# ---------- context request get ----------
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from request; and __fish_seen_subcommand_from get' -s r -l request-id -d 'Request ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from request; and __fish_seen_subcommand_from get' -s c -l collection-id -d 'Collection ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from request; and __fish_seen_subcommand_from get' -s h -l help -d 'display help for command'
# ---------- context request context ----------
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from request; and __fish_seen_subcommand_from context' -s c -l collection-id -d 'Collection ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from request; and __fish_seen_subcommand_from context' -s r -l request-id -d 'Request ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from request; and __fish_seen_subcommand_from context' -s h -l help -d 'display help for command'
# ---------- context folder ----------
complete -c postman -n '__postman_using_subcommand folder get' -a get -d 'Get a folder from a collection'
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from folder' -s h -l help -d 'display help for command'
# ---------- context folder get ----------
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from folder; and __fish_seen_subcommand_from get' -l folder-id -d 'Folder ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from folder; and __fish_seen_subcommand_from get' -s c -l collection-id -d 'Collection ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from folder; and __fish_seen_subcommand_from get' -s h -l help -d 'display help for command'
# ---------- context response ----------
complete -c postman -n '__postman_using_subcommand response get' -a get -d 'Get a saved response example from a collection'
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from response' -s h -l help -d 'display help for command'
# ---------- context response get ----------
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from response; and __fish_seen_subcommand_from get' -l id -d 'Response ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from response; and __fish_seen_subcommand_from get' -s c -l collection-id -d 'Collection ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from response; and __fish_seen_subcommand_from get' -s r -l request-id -d 'Request ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from response; and __fish_seen_subcommand_from get' -s h -l help -d 'display help for command'
# ---------- context workspace ----------
complete -c postman -n '__postman_using_subcommand workspace get' -a get -d 'Get a workspace by ID'
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from workspace' -s h -l help -d 'display help for command'
# ---------- context workspace get ----------
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from get' -s w -l workspace-id -d 'Workspace ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from workspace; and __fish_seen_subcommand_from get' -s h -l help -d 'display help for command'
# ---------- context environment ----------
complete -c postman -n '__postman_using_subcommand environment get' -a get -d 'Get a single environment by ID'
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from environment' -s h -l help -d 'display help for command'
# ---------- context environment get ----------
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from environment; and __fish_seen_subcommand_from get' -s e -l environment-id -d 'Environment ID' -x
complete -c postman -n '__fish_seen_subcommand_from context; and __fish_seen_subcommand_from environment; and __fish_seen_subcommand_from get' -s h -l help -d 'display help for command'

# ---------- search ----------
complete -c postman -n '__postman_using_subcommand search requests collections workspaces flows specs mocks environments' -a requests -d 'Search for requests by name or keyword.'
complete -c postman -n '__postman_using_subcommand search requests collections workspaces flows specs mocks environments' -a collections -d 'Search for collections by name or keyword.'
complete -c postman -n '__postman_using_subcommand search requests collections workspaces flows specs mocks environments' -a workspaces -d 'Search for workspaces by name or keyword.'
complete -c postman -n '__postman_using_subcommand search requests collections workspaces flows specs mocks environments' -a flows -d 'Search for flows by name or keyword.'
complete -c postman -n '__postman_using_subcommand search requests collections workspaces flows specs mocks environments' -a specs -d 'Search for API specs by name or keyword.'
complete -c postman -n '__postman_using_subcommand search requests collections workspaces flows specs mocks environments' -a mocks -d 'Search for mocks by name or keyword.'
complete -c postman -n '__postman_using_subcommand search requests collections workspaces flows specs mocks environments' -a environments -d 'Search for environments by name or keyword.'
complete -c postman -n '__fish_seen_subcommand_from search' -l ownership -d 'Ownership: organization (or org), external, all (default: "organization")' -x
complete -c postman -n '__fish_seen_subcommand_from search' -s n -l limit -d 'Max results per page. Max allowed limit: 25 (default: 10)' -x
complete -c postman -n '__fish_seen_subcommand_from search' -l cursor -d 'Cursor for pagination' -x
complete -c postman -n '__fish_seen_subcommand_from search' -s o -l output -d 'Output format: default (card list), json (detailed JSON) (default: "default")' -x
complete -c postman -n '__fish_seen_subcommand_from search' -l filter -d 'Filter expression (e.g. "workspaceId=ws-123 AND visibility=public")' -x
complete -c postman -n '__fish_seen_subcommand_from search' -l filter-json -d 'Filter as raw JSON. Only a top-level "$and" list of condition objects is supported. "$or" and nested groups are not supported in --filter-json. Each condition: { "<property>": { "<operator>": <value> } }. If both --filter and --filter-json are provided, --filter-json takes precedence.' -x
complete -c postman -n '__fish_seen_subcommand_from search' -s h -l help -d 'display help for command'
# ---------- search requests ----------
complete -c postman -n '__fish_seen_subcommand_from search; and __fish_seen_subcommand_from requests' -s h -l help -d 'display help for command'
# ---------- search collections ----------
complete -c postman -n '__fish_seen_subcommand_from search; and __fish_seen_subcommand_from collections' -s h -l help -d 'display help for command'
# ---------- search workspaces ----------
complete -c postman -n '__fish_seen_subcommand_from search; and __fish_seen_subcommand_from workspaces' -s h -l help -d 'display help for command'
# ---------- search flows ----------
complete -c postman -n '__fish_seen_subcommand_from search; and __fish_seen_subcommand_from flows' -s h -l help -d 'display help for command'
# ---------- search specs ----------
complete -c postman -n '__fish_seen_subcommand_from search; and __fish_seen_subcommand_from specs' -s h -l help -d 'display help for command'
# ---------- search mocks ----------
complete -c postman -n '__fish_seen_subcommand_from search; and __fish_seen_subcommand_from mocks' -s h -l help -d 'display help for command'
# ---------- search environments ----------
complete -c postman -n '__fish_seen_subcommand_from search; and __fish_seen_subcommand_from environments' -s h -l help -d 'display help for command'

# ---------- webhook ----------
complete -c postman -n '__postman_using_subcommand webhook create start pause list delete status forward' -a create -d 'Create a new webhook and print its public URL.'
complete -c postman -n '__postman_using_subcommand webhook create start pause list delete status forward' -a start -d 'Activate a webhook so it can receive requests.'
complete -c postman -n '__postman_using_subcommand webhook create start pause list delete status forward' -a pause -d 'Pause a webhook so it no longer accepts requests.'
complete -c postman -n '__postman_using_subcommand webhook create start pause list delete status forward' -a list -d 'List all webhooks in a workspace.'
complete -c postman -n '__postman_using_subcommand webhook create start pause list delete status forward' -a delete -d 'Permanently delete a webhook.'
complete -c postman -n '__postman_using_subcommand webhook create start pause list delete status forward' -a status -d 'Show details for a webhook.'
complete -c postman -n '__postman_using_subcommand webhook create start pause list delete status forward' -a forward -d 'Forward incoming webhook requests to a local port.'
complete -c postman -n '__fish_seen_subcommand_from webhook' -s h -l help -d 'display help for command'
# ---------- webhook create ----------
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from create' -s t -l title -d 'Name for the webhook (default: "CLI Webhook")' -x
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from create' -s w -l workspace -d 'Postman workspace ID (falls back to .postman/resources.yaml or .postman/config.json)' -x
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from create' -l api-key -d 'Postman API key' -r
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from create' -s h -l help -d 'display help for command'
# ---------- webhook start ----------
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from start' -s w -l workspace -d 'Postman workspace ID' -x
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from start' -l api-key -d 'Postman API key' -r
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from start' -s h -l help -d 'display help for command'
# ---------- webhook pause ----------
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from pause' -s w -l workspace -d 'Postman workspace ID' -x
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from pause' -l api-key -d 'Postman API key' -r
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from pause' -s h -l help -d 'display help for command'
# ---------- webhook list ----------
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from list' -s w -l workspace -d 'Postman workspace ID (falls back to .postman/resources.yaml or .postman/config.json)' -x
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from list' -l api-key -d 'Postman API key' -r
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from list' -s h -l help -d 'display help for command'
# ---------- webhook delete ----------
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from delete' -s w -l workspace -d 'Postman workspace ID' -x
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from delete' -l api-key -d 'Postman API key' -r
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from delete' -s h -l help -d 'display help for command'
# ---------- webhook status ----------
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from status' -s w -l workspace -d 'Postman workspace ID' -x
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from status' -l api-key -d 'Postman API key' -r
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from status' -s h -l help -d 'display help for command'
# ---------- webhook forward ----------
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from forward' -s w -l workspace -d 'Postman workspace ID' -x
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from forward' -l api-key -d 'Postman API key' -r
complete -c postman -n '__fish_seen_subcommand_from webhook; and __fish_seen_subcommand_from forward' -s h -l help -d 'display help for command'
