const HEADER = (version) => `# Bash completion for Postman CLI (postman v${version})
# Auto-generated by scripts/generate.mjs — DO NOT EDIT
# Source: spec/commands.json
# https://github.com/yokawasa/postman-cli-completion
#
# Install:
#   source /path/to/postman.bash
# Or copy into /usr/local/etc/bash_completion.d/ (Homebrew) or
# /etc/bash_completion.d/ (Linux).

# shellcheck shell=bash disable=SC2207

_postman_filematch() {
  local cur="$2"
  COMPREPLY=( $(compgen -f -X "$1" -- "$cur") )
  COMPREPLY+=( $(compgen -d -- "$cur") )
}
`;

const fnName = (parts) => "_postman" + parts.map((p) => "_" + p.replace(/-/g, "_")).join("");

function flagTokens(flag) {
  const tokens = [];
  if (flag.short) tokens.push(flag.short);
  if (flag.long) tokens.push(flag.long);
  return tokens.join(" ");
}

function allFlagsStr(cmd) {
  return (cmd.flags || []).map(flagTokens).filter(Boolean).join(" ");
}

function valueFlags(cmd) {
  return (cmd.flags || []).filter(
    (f) => f.valueType && f.valueType !== "none"
  );
}

function emitValueCases(cmd) {
  const lines = [];
  const vf = valueFlags(cmd);
  if (!vf.length) return lines;
  lines.push(`  case "$prev" in`);
  for (const f of vf) {
    const keys = [];
    if (f.short) keys.push(f.short);
    if (f.long) keys.push(f.long);
    const pat = keys.join("|");
    if (f.valueType === "enum" && f.choices?.length) {
      lines.push(`    ${pat})`);
      lines.push(`      COMPREPLY=( $(compgen -W "${f.choices.join(" ")}" -- "$cur") )`);
      lines.push(`      return 0 ;;`);
    } else if (f.valueType === "file") {
      const pats = f.patterns?.length ? f.patterns : ["*.json"];
      const exts = pats.map((p) => p.replace(/^\*\./, "")).join("|");
      lines.push(`    ${pat})`);
      lines.push(`      _postman_filematch '!*.@(${exts})' "$cur"`);
      lines.push(`      return 0 ;;`);
    } else if (f.valueType === "dir") {
      lines.push(`    ${pat})`);
      lines.push(`      COMPREPLY=( $(compgen -d -- "$cur") )`);
      lines.push(`      return 0 ;;`);
    }
  }
  lines.push(`  esac`);
  return lines;
}

function positionalCompletion(cmd) {
  const p = cmd.positionals?.[cmd.positionals.length - 1];
  if (!p) return [];
  if (p.valueType === "file") {
    const pats = p.patterns?.length ? p.patterns : ["*.json"];
    const exts = pats.map((s) => s.replace(/^\*\./, "")).join("|");
    return [`  _postman_filematch '!*.@(${exts})' "$cur"`];
  }
  if (p.valueType === "dir") {
    return [`  COMPREPLY=( $(compgen -d -- "$cur") )`];
  }
  return [];
}

function emitLeaf(cmd, path) {
  const name = fnName(path);
  const flags = allFlagsStr(cmd);
  const lines = [`${name}() {`];
  lines.push(`  if [[ "$cur" == -* ]]; then`);
  lines.push(`    COMPREPLY=( $(compgen -W "${flags}" -- "$cur") )`);
  lines.push(`    return 0`);
  lines.push(`  fi`);
  lines.push(...emitValueCases(cmd));
  const pos = positionalCompletion(cmd);
  if (pos.length) {
    lines.push(...pos);
  }
  lines.push(`}`);
  return lines.join("\n");
}

function emitDispatcher(cmd, path) {
  const name = fnName(path);
  const subs = cmd.subcommands || [];
  const subNames = subs.flatMap((s) => [s.name, ...(s.aliases || [])]).join(" ");
  const ownFlagsStr = allFlagsStr(cmd) || "-h --help";
  const lines = [`${name}() {`];
  lines.push(`  if [[ -z "$subcmd" ]]; then`);
  lines.push(`    if [[ "$cur" == -* ]]; then`);
  lines.push(`      COMPREPLY=( $(compgen -W "${ownFlagsStr}" -- "$cur") )`);
  lines.push(`    else`);
  lines.push(`      COMPREPLY=( $(compgen -W "${subNames}" -- "$cur") )`);
  lines.push(`    fi`);
  lines.push(`    return 0`);
  lines.push(`  fi`);
  lines.push(`  case "$subcmd" in`);
  for (const sub of subs) {
    const matches = [sub.name, ...(sub.aliases || [])].join("|");
    lines.push(`    ${matches}) ${fnName([...path, sub.name])} ;;`);
  }
  lines.push(`  esac`);
  lines.push(`}`);
  return lines.join("\n");
}

function emitCommand(cmd, path) {
  const parts = [];
  if (cmd.subcommands?.length) {
    parts.push(emitDispatcher(cmd, path));
    for (const sub of cmd.subcommands) {
      parts.push(emitCommand(sub, [...path, sub.name]));
    }
  } else {
    parts.push(emitLeaf(cmd, path));
  }
  return parts.join("\n\n");
}

function emitMain(spec) {
  const topNames = spec.commands.flatMap((c) => [c.name, ...(c.aliases || [])]).join(" ");
  const globals = spec.global.flags.map(flagTokens).join(" ") + " -h --help";

  const lines = [
    `_postman() {`,
    `  local cur prev`,
    `  COMPREPLY=()`,
    `  cur="\${COMP_WORDS[COMP_CWORD]}"`,
    `  prev="\${COMP_WORDS[COMP_CWORD-1]}"`,
    ``,
    `  local top_commands="${topNames}"`,
    `  local global_flags="${globals}"`,
    ``,
    `  local i cmd="" subcmd=""`,
    `  for ((i=1; i<COMP_CWORD; i++)); do`,
    `    case "\${COMP_WORDS[i]}" in -*) continue ;; esac`,
    `    if [[ -z "$cmd" ]]; then`,
    `      cmd="\${COMP_WORDS[i]}"`,
    `    elif [[ -z "$subcmd" ]]; then`,
    `      subcmd="\${COMP_WORDS[i]}"`,
    `      break`,
    `    fi`,
    `  done`,
    ``,
    `  if [[ -z "$cmd" ]]; then`,
    `    if [[ "$cur" == -* ]]; then`,
    `      COMPREPLY=( $(compgen -W "$global_flags" -- "$cur") )`,
    `    else`,
    `      COMPREPLY=( $(compgen -W "$top_commands" -- "$cur") )`,
    `    fi`,
    `    return 0`,
    `  fi`,
    ``,
    `  case "$cmd" in`,
  ];
  for (const c of spec.commands) {
    const matches = [c.name, ...(c.aliases || [])].join("|");
    lines.push(`    ${matches}) ${fnName([c.name])} ;;`);
  }
  lines.push(`  esac`, `}`);
  return lines.join("\n");
}

export function emitBash(spec) {
  const chunks = [HEADER(spec.postmanCliVersion)];
  chunks.push(emitMain(spec));
  for (const c of spec.commands) {
    chunks.push("");
    chunks.push(emitCommand(c, [c.name]));
  }
  chunks.push("");
  chunks.push(`complete -F _postman postman`);
  return chunks.join("\n") + "\n";
}
