const HEADER = (version, topNames) => `# Fish completion for Postman CLI (postman v${version})
# Auto-generated by scripts/generate.mjs — DO NOT EDIT
# Source: spec/commands.json
# https://github.com/yokawasa/postman-cli-completion

function __postman_no_subcommand
    not __fish_seen_subcommand_from ${topNames}
end

function __postman_using_subcommand
    set -l parent $argv[1]
    set -l leaves $argv[2..]
    __fish_seen_subcommand_from $parent
    and not __fish_seen_subcommand_from $leaves
end

`;

const escDesc = (s) =>
  String(s ?? "")
    .replace(/\s+/g, " ")
    .replace(/'/g, "\\'")
    .trim();

function emitGlobalFlag(flag) {
  const parts = [`complete -c postman`];
  parts.push(`-n __postman_no_subcommand`);
  if (flag.short) parts.push(`-s ${flag.short.replace(/^-/, "")}`);
  if (flag.long) parts.push(`-l ${flag.long.replace(/^--/, "")}`);
  if (flag.description) parts.push(`-d '${escDesc(flag.description)}'`);
  if (flag.valueType === "enum" && flag.choices?.length) {
    parts.push(`-x`, `-a '${flag.choices.join(" ")}'`);
  } else if (flag.valueType === "file") {
    parts.push(`-r`);
  } else if (flag.valueType && flag.valueType !== "none") {
    parts.push(`-x`);
  }
  return parts.join(" ");
}

function emitTopCommand(c) {
  const lines = [];
  const names = [c.name, ...(c.aliases || [])];
  for (const n of names) {
    const dStr = n === c.name
      ? c.description
      : `Alias for ${c.name}`;
    lines.push(
      `complete -c postman -n __postman_no_subcommand -a ${n} -d '${escDesc(dStr)}'`
    );
  }
  return lines.join("\n");
}

function condFor(path) {
  if (path.length === 1) {
    return `__fish_seen_subcommand_from ${path[0]}`;
  }
  const parts = path.map(
    (p, i) => `__fish_seen_subcommand_from ${p}`
  );
  return parts.join("; and ");
}

function condListSubs(path, subs) {
  const allNames = subs.flatMap((s) => [s.name, ...(s.aliases || [])]);
  return `__postman_using_subcommand ${path[path.length - 1]} ${allNames.join(" ")}`;
}

function emitSubcommandList(path, subs) {
  const lines = [];
  const cond = condListSubs(path, subs);
  for (const s of subs) {
    const names = [s.name, ...(s.aliases || [])];
    for (const n of names) {
      const desc = n === s.name ? s.description : `Alias for ${s.name}`;
      lines.push(
        `complete -c postman -n '${cond}' -a ${n} -d '${escDesc(desc)}'`
      );
    }
  }
  return lines.join("\n");
}

function emitFlagsAt(path, flags, positionals) {
  if (!flags?.length && !positionals?.length) return "";
  const cond = condFor(path);
  const lines = [];
  for (const f of flags || []) {
    const parts = [`complete -c postman`, `-n '${cond}'`];
    if (f.short) parts.push(`-s ${f.short.replace(/^-/, "")}`);
    if (f.long) parts.push(`-l ${f.long.replace(/^--/, "")}`);
    if (f.description) parts.push(`-d '${escDesc(f.description)}'`);
    if (f.valueType === "enum" && f.choices?.length) {
      parts.push(`-x`, `-a '${f.choices.join(" ")}'`);
    } else if (f.valueType === "file") {
      parts.push(`-r`);
    } else if (f.valueType && f.valueType !== "none") {
      parts.push(`-x`);
    }
    lines.push(parts.join(" "));
  }
  const lastPos = positionals?.[positionals.length - 1];
  if (lastPos && lastPos.valueType === "file") {
    const pats = lastPos.patterns?.length ? lastPos.patterns : ["*.json"];
    const exts = pats.map((s) => s.replace(/^\*\./, "")).join(" ");
    lines.push(
      `complete -c postman -n '${cond}' -r -k -a '(__fish_complete_suffix .${pats[0].replace(/^\*\./, "")})'`
    );
  }
  return lines.join("\n");
}

function emitCommand(cmd, path) {
  const sections = [`# ---------- ${path.join(" ")} ----------`];
  if (cmd.subcommands?.length) {
    sections.push(emitSubcommandList(path, cmd.subcommands));
    if (cmd.flags?.length || cmd.positionals?.length) {
      sections.push(emitFlagsAt(path, cmd.flags, cmd.positionals));
    }
    for (const sub of cmd.subcommands) {
      sections.push(emitCommand(sub, [...path, sub.name]));
    }
  } else {
    sections.push(emitFlagsAt(path, cmd.flags, cmd.positionals));
  }
  return sections.filter(Boolean).join("\n");
}

export function emitFish(spec) {
  const topNames = spec.commands
    .flatMap((c) => [c.name, ...(c.aliases || [])])
    .join(" ");
  const chunks = [HEADER(spec.postmanCliVersion, topNames).trimEnd()];
  chunks.push("");
  chunks.push("# ---------- Global flags ----------");
  for (const f of spec.global.flags) chunks.push(emitGlobalFlag(f));
  chunks.push("");
  chunks.push("# ---------- Top-level commands ----------");
  for (const c of spec.commands) chunks.push(emitTopCommand(c));
  for (const c of spec.commands) {
    chunks.push("");
    chunks.push(emitCommand(c, [c.name]));
  }
  return chunks.join("\n") + "\n";
}
