const HEADER = (version) => `#compdef postman
compdef _postman postman
# Zsh completion for Postman CLI (postman v${version})
# Auto-generated by scripts/generate.mjs — DO NOT EDIT
# Source: spec/commands.json
# https://github.com/yokawasa/postman-cli-completion

`;

const FOOTER = `
# When loaded via fpath + compinit, the file body becomes the function body of
# \`_postman\`. In that case \`funcstack[1]\` is \`_postman\` and we must actually
# invoke the completion. When sourced directly, this is a no-op — \`_postman\`
# is registered via \`compdef\` at the top of this file and called later by the
# completion system on TAB.
if [ "$funcstack[1]" = "_postman" ]; then
    _postman
fi
`;

const esc = (s) =>
  String(s ?? "")
    .replace(/'/g, "'\\''")
    .replace(/[\[\]:]/g, "\\$&");

const desc = (s) => esc((s || "").replace(/\s+/g, " ").trim());

const fnName = (parts) => "_postman" + parts.map((p) => "_" + p.replace(/-/g, "_")).join("");

// zsh parses a trailing parenthesized group as a glob qualifier, so a
// single-alternative pattern like "*.(json)" errors ("unknown file attribute: j")
// and yields no completions. Emit "*.json" for one extension and only use the
// "(a|b)" alternation form (forced by the "|") when there are several.
const filesGlob = (exts) =>
  exts.length === 1 ? `*.${exts[0]}` : `*.(${exts.join("|")})`;

function filesArg(flag) {
  if (flag.valueType === "file") {
    const pats = flag.patterns?.length ? flag.patterns : ["*.json"];
    const exts = pats.map((p) => p.replace(/^\*\./, ""));
    return `_files -g "${filesGlob(exts)}"`;
  }
  if (flag.valueType === "dir") return `_files -/`;
  if (flag.valueType === "enum" && flag.choices?.length) {
    return `(${flag.choices.join(" ")})`;
  }
  return "";
}

function flagSpec(flag) {
  const description = `[${desc(flag.description)}]`;
  const argName = esc(flag.valueName || "value");
  const action = filesArg(flag);
  const hasValue = flag.valueType && flag.valueType !== "none";
  const tail = hasValue
    ? (action ? `${description}:${argName}:${action}` : `${description}:${argName}`)
    : description;
  if (flag.short && flag.long) {
    return `'(${flag.short} ${flag.long})'{${flag.short},${flag.long}}'${tail}'`;
  }
  return `'${flag.short || flag.long}${tail}'`;
}

function positionalSpec(positionals) {
  if (!positionals?.length) return "";
  const p = positionals[positionals.length - 1];
  const argName = esc(p.name);
  if (p.valueType === "file") {
    const patterns = p.patterns?.length ? p.patterns : ["*.json"];
    const exts = patterns.map((s) => s.replace(/^\*\./, ""));
    return `'*:${argName}:_files -g "${filesGlob(exts)}"'`;
  }
  if (p.valueType === "dir") return `'*:${argName}:_files -/'`;
  return `'*:${argName}:'`;
}

function emitLeaf(cmd, path) {
  const name = fnName(path);
  const flags = (cmd.flags || []).map(flagSpec);
  const positional = positionalSpec(cmd.positionals);
  const lines = [`${name}() {`, `  _arguments \\`];
  const specs = [...flags];
  if (positional) specs.push(positional);
  for (let i = 0; i < specs.length; i++) {
    lines.push(`    ${specs[i]}${i < specs.length - 1 ? " \\" : ""}`);
  }
  lines.push(`}`);
  return lines.join("\n");
}

function emitDispatcher(cmd, path) {
  const name = fnName(path);
  const subs = cmd.subcommands || [];
  const ownFlags = (cmd.flags || []).map(flagSpec);
  if (!(cmd.flags || []).some((f) => f.long === "--help" || f.short === "-h")) {
    ownFlags.push(`'(-h --help)'{-h,--help}'[display help for command]'`);
  }
  const lines = [
    `${name}() {`,
    `  local context state state_descr line`,
    `  typeset -A opt_args`,
    `  _arguments -C \\`,
  ];
  for (const f of ownFlags) lines.push(`    ${f} \\`);
  lines.push(`    '1: :${name}_commands' \\`);
  lines.push(`    '*::arg:->args'`);
  lines.push(`  case $state in`, `    args)`, `      case $words[1] in`);
  for (const sub of subs) {
    const matches = [sub.name, ...(sub.aliases || [])].join("|");
    lines.push(`        ${matches}) ${fnName([...path, sub.name])} ;;`);
  }
  lines.push(`      esac`, `      ;;`, `  esac`, `}`, ``);

  lines.push(`${name}_commands() {`, `  local -a sub`, `  sub=(`);
  for (const sub of subs) {
    lines.push(`    '${esc(sub.name)}:${desc(sub.description)}'`);
    for (const a of sub.aliases || []) {
      lines.push(`    '${esc(a)}:Alias for ${esc(sub.name)}'`);
    }
  }
  lines.push(`  )`, `  _describe -t commands '${path[path.length - 1] || "postman"} command' sub`, `}`);
  return lines.join("\n");
}

function emitCommand(cmd, path) {
  const parts = [];
  if (cmd.subcommands?.length) {
    parts.push(emitDispatcher(cmd, path));
    for (const sub of cmd.subcommands) {
      parts.push(emitCommand(sub, [...path, sub.name]));
    }
  } else {
    parts.push(emitLeaf(cmd, path));
  }
  return parts.join("\n\n");
}

function emitTopDispatch(spec) {
  const lines = [
    `_postman() {`,
    `  local context state state_descr line`,
    `  typeset -A opt_args`,
    ``,
    `  _arguments -C \\`,
  ];

  const flagSpecs = spec.global.flags.map(flagSpec);
  for (const f of flagSpecs) lines.push(`    ${f} \\`);
  lines.push(`    '1: :_postman_commands' \\`);
  lines.push(`    '*::arg:->args'`);
  lines.push(``, `  case $state in`, `    args)`, `      case $words[1] in`);
  for (const c of spec.commands) {
    const matches = [c.name, ...(c.aliases || [])].join("|");
    lines.push(`        ${matches}) ${fnName([c.name])} ;;`);
  }
  lines.push(`      esac`, `      ;;`, `  esac`, `}`);
  return lines.join("\n");
}

function emitTopCommands(spec) {
  const lines = [`_postman_commands() {`, `  local -a commands`, `  commands=(`];
  for (const c of spec.commands) {
    lines.push(`    '${esc(c.name)}:${desc(c.description)}'`);
    for (const a of c.aliases || []) {
      lines.push(`    '${esc(a)}:Alias for ${esc(c.name)}'`);
    }
  }
  lines.push(`  )`, `  _describe -t commands 'postman command' commands`, `}`);
  return lines.join("\n");
}

export function emitZsh(spec) {
  const chunks = [HEADER(spec.postmanCliVersion).trimEnd()];
  chunks.push("");
  chunks.push(emitTopDispatch(spec));
  chunks.push("");
  chunks.push(emitTopCommands(spec));
  for (const c of spec.commands) {
    chunks.push("");
    chunks.push(emitCommand(c, [c.name]));
  }
  chunks.push(FOOTER);
  return chunks.join("\n");
}
